/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 10/24/2016 11:53:06 PM
Database Connection: EG1RDMDBDEV01.amr.corp.intel.com\DEALSDEV,3181, MyDeals
Machine Name: PWECKENR-MOBL5
User: AMR\pweckenr
*/


using System;
using System.Data;
using Intel.Opaque.DBAccess;
using System.Data.SqlClient;



namespace Intel.MyDeals.DataAccessLib.StoredProcedures.MyDeals {
	namespace dbo {

		///<summary>
		/// ID: 1573580644
		/// Modified: 10/11/2016 9:02:19 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_CUSTOM_ERRMSG : SP {
			public PR_CUSTOM_ERRMSG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_CUSTOM_ERRMSG]";
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String Msg {
				set { SetParmeter("Msg", value); }
				get { return (String)GetParameter("Msg"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean RaiseError {
				set { SetParmeter("RaiseError", value); }
				get { return (Boolean)GetParameter("RaiseError"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 SourceObjectID {
				set { SetParmeter("SourceObjectID", value); }
				get { return (Int32)GetParameter("SourceObjectID"); }
			}
		}

		///<summary>
		/// ID: 1525580473
		/// Modified: 10/8/2016 9:37:16 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_DEL_POC_EMP : SP {
			public PR_DEL_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DEL_POC_EMP]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 emp_sid {
				set { SetParmeter("emp_sid", value); }
				get { return (Int32)GetParameter("emp_sid"); }
			}
		}

		///<summary>
		/// ID: 354100302
		/// Modified: 10/11/2016 2:03:56 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_DROP_TEMP_TBL : SP {
			public PR_DROP_TEMP_TBL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DROP_TEMP_TBL]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String TableName {
				set { SetParmeter("TableName", value); }
				get { return (String)GetParameter("TableName"); }
			}
		}

		///<summary>
		/// ID: 1125579048
		/// Modified: 10/5/2016 9:53:50 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_ENSURE_EXIST : SP {
			public PR_ENSURE_EXIST() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_ENSURE_EXIST]";
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String Type {
				set { SetParmeter("Type", value); }
				get { return (String)GetParameter("Type"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String ObjectName {
				set { SetParmeter("ObjectName", value); }
				get { return (String)GetParameter("ObjectName"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 2000, false)]
			public String SynName {
				set { SetParmeter("SynName", value); }
				get { return (String)GetParameter("SynName"); }
			}
		}

		///<summary>
		/// ID: 562101043
		/// Modified: 10/14/2016 9:11:12 AM
		/// Parameters: 1
		///</summary>
		public partial class PR_GET_CONSTANTS : SP {
			public PR_GET_CONSTANTS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_CONSTANTS]";
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 50, false)]
			public String cnst_nm {
				set { SetParmeter("cnst_nm", value); }
				get { return (String)GetParameter("cnst_nm"); }
			}
		}

		///<summary>
		/// ID: 1189579276
		/// Modified: 10/7/2016 12:56:57 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_GET_POC_EMP : SP {
			public PR_GET_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_POC_EMP]";
			}
		}

		///<summary>
		/// ID: 1861581670
		/// Modified: 10/11/2016 11:44:15 AM
		/// Parameters: 7
		///</summary>
		public partial class PR_MANAGE_CONSTANT_VALUES : SP {
			public PR_MANAGE_CONSTANT_VALUES() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_CONSTANT_VALUES]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 50, false)]
			public String cnst_nm {
				set { SetParmeter("cnst_nm", value); }
				get { return (String)GetParameter("cnst_nm"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Int32 cnst_sid {
				set { SetParmeter("cnst_sid", value); }
				get { return (Int32)GetParameter("cnst_sid"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", -1, false)]
			public String cnst_desc {
				set { SetParmeter("cnst_desc", value); }
				get { return (String)GetParameter("cnst_desc"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", -1, false)]
			public String cnst_val_txt {
				set { SetParmeter("cnst_val_txt", value); }
				get { return (String)GetParameter("cnst_val_txt"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Boolean ui_updatable {
				set { SetParmeter("ui_updatable", value); }
				get { return (Boolean)GetParameter("ui_updatable"); }
			}
		}

		///<summary>
		/// ID: 613577224
		/// Modified: 10/3/2016 11:23:34 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_PING_DB : SP {
			public PR_PING_DB() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_PING_DB]";
			}
		}

		///<summary>
		/// ID: 1205579333
		/// Modified: 10/8/2016 9:58:42 PM
		/// Parameters: 3
		///</summary>
		public partial class PR_SET_POC_EMP : SP {
			public PR_SET_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SET_POC_EMP]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 emp_sid {
				set { SetParmeter("emp_sid", value); }
				get { return (Int32)GetParameter("emp_sid"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 100, false)]
			public String first_nm {
				set { SetParmeter("first_nm", value); }
				get { return (String)GetParameter("first_nm"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 100, false)]
			public String last_nm {
				set { SetParmeter("last_nm", value); }
				get { return (String)GetParameter("last_nm"); }
			}
		}
	}


}

