/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 11/28/2016 3:00:36 PM
Database Connection: EG1RDMDBDEV01.amr.corp.intel.com\DEALSDEV,3180, MyDeals
Machine Name: JJYEH-MOBL
User: AMR\jjyeh
*/


using System;
using System.Data;
using Intel.Opaque.DBAccess;
using System.Data.SqlClient;



namespace Intel.MyDeals.DataAccessLib.StoredProcedures.MyDeals {
	namespace dbo {

		///<summary>
		/// ID: 1618104805
		/// Modified: 11/2/2016 12:43:15 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_ALTER_TABLE_SAVER : SP {
			public PR_ALTER_TABLE_SAVER() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_ALTER_TABLE_SAVER]";
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Boolean IS_SAVE {
				set { SetParmeter("IS_SAVE", value); }
				get { return (Boolean)GetParameter("IS_SAVE"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String TABLE_NAME {
				set { SetParmeter("TABLE_NAME", value); }
				get { return (String)GetParameter("TABLE_NAME"); }
			}
		}

		///<summary>
		/// ID: 1470628282
		/// Modified: 11/2/2016 1:53:45 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_APP_STATUS : SP {
			public PR_APP_STATUS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_APP_STATUS]";
			}
		}

		///<summary>
		/// ID: 1538104520
		/// Modified: 11/2/2016 8:41:10 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_CDMS_DROP_OBJ : SP {
			public PR_CDMS_DROP_OBJ() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_CDMS_DROP_OBJ]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String ObjectName {
				set { SetParmeter("ObjectName", value); }
				get { return (String)GetParameter("ObjectName"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean DropReplication {
				set { SetParmeter("DropReplication", value); }
				get { return (Boolean)GetParameter("DropReplication"); }
			}

			///<summary>
			/// DataType: varchar(1000)
			/// Mode: IN
			/// Max Length: 1000
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 1000, false)]
			public String Key {
				set { SetParmeter("Key", value); }
				get { return (String)GetParameter("Key"); }
			}
		}

		///<summary>
		/// ID: 1490104349
		/// Modified: 11/2/2016 12:42:05 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_CDMS_PRINT : SP {
			public PR_CDMS_PRINT() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_CDMS_PRINT]";
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String txt {
				set { SetParmeter("txt", value); }
				get { return (String)GetParameter("txt"); }
			}
		}

		///<summary>
		/// ID: 1650104919
		/// Modified: 11/2/2016 12:44:12 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_CHK_OBJ_NM : SP {
			public PR_CHK_OBJ_NM() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_CHK_OBJ_NM]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String ObjectName {
				set { SetParmeter("ObjectName", value); }
				get { return (String)GetParameter("ObjectName"); }
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 128, false)]
			public String Type {
				set { SetParmeter("Type", value); }
				get { return (String)GetParameter("Type"); }
			}
		}

		///<summary>
		/// ID: 1573580644
		/// Modified: 11/15/2016 10:02:03 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_CUSTOM_ERRMSG : SP {
			public PR_CUSTOM_ERRMSG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_CUSTOM_ERRMSG]";
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String Msg {
				set { SetParmeter("Msg", value); }
				get { return (String)GetParameter("Msg"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean RaiseError {
				set { SetParmeter("RaiseError", value); }
				get { return (Boolean)GetParameter("RaiseError"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 SourceObjectID {
				set { SetParmeter("SourceObjectID", value); }
				get { return (Int32)GetParameter("SourceObjectID"); }
			}
		}

		///<summary>
		/// ID: 1666104976
		/// Modified: 11/2/2016 1:32:15 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_DBG_INS_TEMPLATE : SP {
			public PR_DBG_INS_TEMPLATE() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DBG_INS_TEMPLATE]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String TABLE_NAME {
				set { SetParmeter("TABLE_NAME", value); }
				get { return (String)GetParameter("TABLE_NAME"); }
			}

			///<summary>
			/// DataType: varchar(10)
			/// Mode: IN
			/// Max Length: 10
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 10, false)]
			public String MODE {
				set { SetParmeter("MODE", value); }
				get { return (String)GetParameter("MODE"); }
			}
		}

		///<summary>
		/// ID: 1092198941
		/// Modified: 11/4/2016 2:41:04 PM
		/// Parameters: 7
		///</summary>
		public partial class PR_DBG_TOGGLE_IDX_TR : SP {
			public PR_DBG_TOGGLE_IDX_TR() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DBG_TOGGLE_IDX_TR]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String TableName {
				set { SetParmeter("TableName", value); }
				get { return (String)GetParameter("TableName"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean ToggleOn {
				set { SetParmeter("ToggleOn", value); }
				get { return (Boolean)GetParameter("ToggleOn"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Boolean IncludeIndexes {
				set { SetParmeter("IncludeIndexes", value); }
				get { return (Boolean)GetParameter("IncludeIndexes"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Boolean IncludeClustered {
				set { SetParmeter("IncludeClustered", value); }
				get { return (Boolean)GetParameter("IncludeClustered"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 0, false)]
			public Boolean IncludePK {
				set { SetParmeter("IncludePK", value); }
				get { return (Boolean)GetParameter("IncludePK"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 0, false)]
			public Boolean IncludeUQ {
				set { SetParmeter("IncludeUQ", value); }
				get { return (Boolean)GetParameter("IncludeUQ"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Boolean IncludeTriggers {
				set { SetParmeter("IncludeTriggers", value); }
				get { return (Boolean)GetParameter("IncludeTriggers"); }
			}
		}

		///<summary>
		/// ID: 658101385
		/// Modified: 11/7/2016 1:16:48 PM
		/// Parameters: 4
		///</summary>
		public partial class PR_DEAL_COMMON_PORTAL : SP {
			public PR_DEAL_COMMON_PORTAL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DEAL_COMMON_PORTAL]";
			}

			///<summary>
			/// DataType: varchar(8)
			/// Mode: IN
			/// Max Length: 8
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 8, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 100, false)]
			public String sp_to_run {
				set { SetParmeter("sp_to_run", value); }
				get { return (String)GetParameter("sp_to_run"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", -1, false)]
			public String sp_parameters_xml {
				set { SetParmeter("sp_parameters_xml", value); }
				get { return (String)GetParameter("sp_parameters_xml"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Boolean IsDebugEnabled {
				set { SetParmeter("IsDebugEnabled", value); }
				get { return (Boolean)GetParameter("IsDebugEnabled"); }
			}
		}

		///<summary>
		/// ID: 766625774
		/// Modified: 11/1/2016 8:55:56 AM
		/// Parameters: 1
		///</summary>
		public partial class PR_DEAL_GET_TBL_DEF : SP {
			public PR_DEAL_GET_TBL_DEF() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DEAL_GET_TBL_DEF]";
			}

			///<summary>
			/// DataType: varchar(200)
			/// Mode: IN
			/// Max Length: 200
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 200, false)]
			public String tble_nm {
				set { SetParmeter("tble_nm", value); }
				get { return (String)GetParameter("tble_nm"); }
			}
		}

		///<summary>
		/// ID: 935674381
		/// Modified: 11/4/2016 2:50:20 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_DEL_DB_LOG : SP {
			public PR_DEL_DB_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DEL_DB_LOG]";
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 50, false)]
			public String in_msg_src {
				set { SetParmeter("in_msg_src", value); }
				get { return (String)GetParameter("in_msg_src"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 in_days_to_del {
				set { SetParmeter("in_days_to_del", value); }
				get { return (Int32)GetParameter("in_days_to_del"); }
			}
		}

		///<summary>
		/// ID: 1525580473
		/// Modified: 10/8/2016 9:37:16 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_DEL_POC_EMP : SP {
			public PR_DEL_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DEL_POC_EMP]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 emp_sid {
				set { SetParmeter("emp_sid", value); }
				get { return (Int32)GetParameter("emp_sid"); }
			}
		}

		///<summary>
		/// ID: 2137774673
		/// Modified: 11/25/2016 1:28:18 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_DQMF_INS_USE_CASE_MDATA : SP {
			public PR_DQMF_INS_USE_CASE_MDATA() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DQMF_INS_USE_CASE_MDATA]";
			}

			///<summary>
			/// DataType: varchar(23)
			/// Mode: IN
			/// Max Length: 23
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 23, false)]
			public String dq_perd {
				set { SetParmeter("dq_perd", value); }
				get { return (String)GetParameter("dq_perd"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 op_in_i_dq_use_case_id {
				set { SetParmeter("op_in_i_dq_use_case_id", value); }
				get { return (Int32)GetParameter("op_in_i_dq_use_case_id"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", -1, false)]
			public String customsummaryemailmessage {
				set { SetParmeter("customsummaryemailmessage", value); }
				get { return (String)GetParameter("customsummaryemailmessage"); }
			}
		}

		///<summary>
		/// ID: 1378103950
		/// Modified: 10/27/2016 8:42:16 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_DROP_INDEX : SP {
			public PR_DROP_INDEX() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DROP_INDEX]";
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String IndexName {
				set { SetParmeter("IndexName", value); }
				get { return (String)GetParameter("IndexName"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String TableName {
				set { SetParmeter("TableName", value); }
				get { return (String)GetParameter("TableName"); }
			}
		}

		///<summary>
		/// ID: 354100302
		/// Modified: 10/11/2016 2:03:56 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_DROP_TEMP_TBL : SP {
			public PR_DROP_TEMP_TBL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_DROP_TEMP_TBL]";
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 2000, false)]
			public String TableName {
				set { SetParmeter("TableName", value); }
				get { return (String)GetParameter("TableName"); }
			}
		}

		///<summary>
		/// ID: 1125579048
		/// Modified: 10/5/2016 9:53:50 AM
		/// Parameters: 3
		///</summary>
		public partial class PR_ENSURE_EXIST : SP {
			public PR_ENSURE_EXIST() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_ENSURE_EXIST]";
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String Type {
				set { SetParmeter("Type", value); }
				get { return (String)GetParameter("Type"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String ObjectName {
				set { SetParmeter("ObjectName", value); }
				get { return (String)GetParameter("ObjectName"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 2000, false)]
			public String SynName {
				set { SetParmeter("SynName", value); }
				get { return (String)GetParameter("SynName"); }
			}
		}

		///<summary>
		/// ID: 2018106230
		/// Modified: 10/31/2016 10:47:02 AM
		/// Parameters: 5
		///</summary>
		public partial class PR_EXP_TBL : SP {
			public PR_EXP_TBL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_EXP_TBL]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 TABLE_ID {
				set { SetParmeter("TABLE_ID", value); }
				get { return (Int32)GetParameter("TABLE_ID"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String FQ_TABLE_NAME {
				set { SetParmeter("FQ_TABLE_NAME", value); }
				get { return (String)GetParameter("FQ_TABLE_NAME"); }
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 128, false)]
			public String DB_NAME {
				set { SetParmeter("DB_NAME", value); }
				get { return (String)GetParameter("DB_NAME"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Boolean FOR_PRINT_TO {
				set { SetParmeter("FOR_PRINT_TO", value); }
				get { return (Boolean)GetParameter("FOR_PRINT_TO"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 0, false)]
			public Boolean TO_TEMP_ONLY {
				set { SetParmeter("TO_TEMP_ONLY", value); }
				get { return (Boolean)GetParameter("TO_TEMP_ONLY"); }
			}
		}

		///<summary>
		/// ID: 2034106287
		/// Modified: 10/31/2016 11:20:05 AM
		/// Parameters: 2
		///</summary>
		public partial class PR_FMT_HTML_TBL : SP {
			public PR_FMT_HTML_TBL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_FMT_HTML_TBL]";
				OutputParameterCount = 1;
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String TEMP_TBL_NM {
				set { SetParmeter("TEMP_TBL_NM", value); }
				get { return (String)GetParameter("TEMP_TBL_NM"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: INOUT
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.InputOutput", -1, false)]
			public String HTML_TABLE {
				set { SetParmeter("HTML_TABLE", value); }
				get { return (String)GetParameter("HTML_TABLE"); }
			}
		}

		///<summary>
		/// ID: 825769999
		/// Modified: 11/21/2016 4:03:40 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_GEN_APP_PRCSS_DIM_HR : SP {
			public PR_GEN_APP_PRCSS_DIM_HR() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GEN_APP_PRCSS_DIM_HR]";
			}

			///<summary>
			/// DataType: varchar(80)
			/// Mode: IN
			/// Max Length: 80
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 80, false)]
			public String IN_DIM_CD {
				set { SetParmeter("IN_DIM_CD", value); }
				get { return (String)GetParameter("IN_DIM_CD"); }
			}
		}

		///<summary>
		/// ID: 1325247776
		/// Modified: 11/17/2016 12:22:42 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_GEN_TRIG_HIST : SP {
			public PR_GEN_TRIG_HIST() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GEN_TRIG_HIST]";
			}

			///<summary>
			/// DataType: varchar(10)
			/// Mode: IN
			/// Max Length: 10
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 10, false)]
			public String IN_SCHMA_NM {
				set { SetParmeter("IN_SCHMA_NM", value); }
				get { return (String)GetParameter("IN_SCHMA_NM"); }
			}

			///<summary>
			/// DataType: varchar(80)
			/// Mode: IN
			/// Max Length: 80
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 80, false)]
			public String IN_TBL_NM {
				set { SetParmeter("IN_TBL_NM", value); }
				get { return (String)GetParameter("IN_TBL_NM"); }
			}
		}

		///<summary>
		/// ID: 562101043
		/// Modified: 11/7/2016 10:00:21 AM
		/// Parameters: 1
		///</summary>
		public partial class PR_GET_CONSTANTS : SP {
			public PR_GET_CONSTANTS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_CONSTANTS]";
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 50, false)]
			public String cnst_nm {
				set { SetParmeter("cnst_nm", value); }
				get { return (String)GetParameter("cnst_nm"); }
			}
		}

		///<summary>
		/// ID: 1257771538
		/// Modified: 11/24/2016 9:01:12 AM
		/// Parameters: 4
		///</summary>
		public partial class PR_GET_CUST_CLNDR_QTR : SP {
			public PR_GET_CUST_CLNDR_QTR() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_CUST_CLNDR_QTR]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 CUST_MBR_SID {
				set { SetParmeter("CUST_MBR_SID", value); }
				get { return (Int32)GetParameter("CUST_MBR_SID"); }
			}

			///<summary>
			/// DataType: smallint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int16 YR_NBR {
				set { SetParmeter("YR_NBR", value); }
				get { return (Int16)GetParameter("YR_NBR"); }
			}

			///<summary>
			/// DataType: smallint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int16 QTR_NBR {
				set { SetParmeter("QTR_NBR", value); }
				get { return (Int16)GetParameter("QTR_NBR"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public DateTime DTM {
				set { SetParmeter("DTM", value); }
				get { return (DateTime)GetParameter("DTM"); }
			}
		}

		///<summary>
		/// ID: 1108198998
		/// Modified: 11/4/2016 3:11:14 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_GET_LOG_CONFIG_DATA : SP {
			public PR_GET_LOG_CONFIG_DATA() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_LOG_CONFIG_DATA]";
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 50, false)]
			public String in_msg_src {
				set { SetParmeter("in_msg_src", value); }
				get { return (String)GetParameter("in_msg_src"); }
			}
		}

		///<summary>
		/// ID: 1189579276
		/// Modified: 10/7/2016 12:56:57 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_GET_POC_EMP : SP {
			public PR_GET_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GET_POC_EMP]";
			}
		}

		///<summary>
		/// ID: 2114106572
		/// Modified: 10/31/2016 1:10:01 PM
		/// Parameters: 7
		///</summary>
		public partial class PR_GREP : SP {
			public PR_GREP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_GREP]";
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String TextToFind {
				set { SetParmeter("TextToFind", value); }
				get { return (String)GetParameter("TextToFind"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 DisplayLevel {
				set { SetParmeter("DisplayLevel", value); }
				get { return (Int32)GetParameter("DisplayLevel"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 Lead {
				set { SetParmeter("Lead", value); }
				get { return (Int32)GetParameter("Lead"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Boolean SearchJobsToo {
				set { SetParmeter("SearchJobsToo", value); }
				get { return (Boolean)GetParameter("SearchJobsToo"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", -1, false)]
			public String IncludeObjects {
				set { SetParmeter("IncludeObjects", value); }
				get { return (String)GetParameter("IncludeObjects"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", -1, false)]
			public String ExcludeObjects {
				set { SetParmeter("ExcludeObjects", value); }
				get { return (String)GetParameter("ExcludeObjects"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Boolean SynSearch {
				set { SetParmeter("SynSearch", value); }
				get { return (Boolean)GetParameter("SynSearch"); }
			}
		}

		///<summary>
		/// ID: 1175675236
		/// Modified: 11/8/2016 12:20:07 PM
		/// Parameters: 7
		///</summary>
		public partial class PR_INS_BTCH_LD_LOG : SP {
			public PR_INS_BTCH_LD_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_INS_BTCH_LD_LOG]";
				OutputParameterCount = 1;
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 255, false)]
			public String IN_PKG_NM {
				set { SetParmeter("IN_PKG_NM", value); }
				get { return (String)GetParameter("IN_PKG_NM"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 50, false)]
			public String IN_MCHN_NM {
				set { SetParmeter("IN_MCHN_NM", value); }
				get { return (String)GetParameter("IN_MCHN_NM"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public DateTime IN_CNTN_STRT_DTM {
				set { SetParmeter("IN_CNTN_STRT_DTM", value); }
				get { return (DateTime)GetParameter("IN_CNTN_STRT_DTM"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public DateTime IN_PKG_STRT_DTM {
				set { SetParmeter("IN_PKG_STRT_DTM", value); }
				get { return (DateTime)GetParameter("IN_PKG_STRT_DTM"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 0, false)]
			public DateTime IN_PKG_END_DTM {
				set { SetParmeter("IN_PKG_END_DTM", value); }
				get { return (DateTime)GetParameter("IN_PKG_END_DTM"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: INOUT
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.InputOutput", 0, false)]
			public Int32 OUT_JOB_SID {
				set { SetParmeter("OUT_JOB_SID", value); }
				get { return (Int32)GetParameter("OUT_JOB_SID"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 50, false)]
			public String IN_RUN_STS {
				set { SetParmeter("IN_RUN_STS", value); }
				get { return (String)GetParameter("IN_RUN_STS"); }
			}
		}

		///<summary>
		/// ID: 967674495
		/// Modified: 11/14/2016 8:56:13 AM
		/// Parameters: 17
		///</summary>
		public partial class PR_INS_DB_LOG : SP {
			public PR_INS_DB_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_INS_DB_LOG]";
				OutputParameterCount = 1;
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 in_step {
				set { SetParmeter("in_step", value); }
				get { return (Int32)GetParameter("in_step"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public DateTime in_log_dtm {
				set { SetParmeter("in_log_dtm", value); }
				get { return (DateTime)GetParameter("in_log_dtm"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 50, false)]
			public String in_lgn_nm {
				set { SetParmeter("in_lgn_nm", value); }
				get { return (String)GetParameter("in_lgn_nm"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 50, false)]
			public String in_usr_nm {
				set { SetParmeter("in_usr_nm", value); }
				get { return (String)GetParameter("in_usr_nm"); }
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 255, false)]
			public String in_clnt_mchn_nm {
				set { SetParmeter("in_clnt_mchn_nm", value); }
				get { return (String)GetParameter("in_clnt_mchn_nm"); }
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 128, false)]
			public String in_srvr {
				set { SetParmeter("in_srvr", value); }
				get { return (String)GetParameter("in_srvr"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 50, false)]
			public String in_msg_src {
				set { SetParmeter("in_msg_src", value); }
				get { return (String)GetParameter("in_msg_src"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", -1, false)]
			public String in_mthd {
				set { SetParmeter("in_mthd", value); }
				get { return (String)GetParameter("in_mthd"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", -1, false)]
			public String in_msg {
				set { SetParmeter("in_msg", value); }
				get { return (String)GetParameter("in_msg"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(10, "ParameterDirection.Input", 0, false)]
			public DateTime in_strt_dtm {
				set { SetParmeter("in_strt_dtm", value); }
				get { return (DateTime)GetParameter("in_strt_dtm"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(11, "ParameterDirection.Input", 0, false)]
			public DateTime in_end_dtm {
				set { SetParmeter("in_end_dtm", value); }
				get { return (DateTime)GetParameter("in_end_dtm"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(12, "ParameterDirection.Input", 0, false)]
			public Int32 in_rec_cnt {
				set { SetParmeter("in_rec_cnt", value); }
				get { return (Int32)GetParameter("in_rec_cnt"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(13, "ParameterDirection.Input", 0, false)]
			public Int32 in_thrd_id {
				set { SetParmeter("in_thrd_id", value); }
				get { return (Int32)GetParameter("in_thrd_id"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(14, "ParameterDirection.Input", 0, false)]
			public Int32 in_is_zip {
				set { SetParmeter("in_is_zip", value); }
				get { return (Int32)GetParameter("in_is_zip"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(15, "ParameterDirection.Input", -1, false)]
			public String in_err_msg {
				set { SetParmeter("in_err_msg", value); }
				get { return (String)GetParameter("in_err_msg"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(16, "ParameterDirection.Input", 0, false)]
			public Int32 in_wwid {
				set { SetParmeter("in_wwid", value); }
				get { return (Int32)GetParameter("in_wwid"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: INOUT
			///</summary>
			[SQLParameterAttribute(17, "ParameterDirection.InputOutput", 0, false)]
			public Int32 in_log_sid {
				set { SetParmeter("in_log_sid", value); }
				get { return (Int32)GetParameter("in_log_sid"); }
			}
		}

		///<summary>
		/// ID: 350624292
		/// Modified: 10/31/2016 3:55:47 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_LD_STG_DIM_GSLD : SP {
			public PR_LD_STG_DIM_GSLD() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_LD_STG_DIM_GSLD]";
			}
		}

		///<summary>
		/// ID: 1326627769
		/// Modified: 11/2/2016 1:02:02 AM
		/// Parameters: 0
		///</summary>
		public partial class pr_ld_stg_prd_edw_dtl : SP {
			public pr_ld_stg_prd_edw_dtl() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[pr_ld_stg_prd_edw_dtl]";
			}
		}

		///<summary>
		/// ID: 1342627826
		/// Modified: 11/2/2016 12:42:19 AM
		/// Parameters: 0
		///</summary>
		public partial class Pr_ld_stg_prd_gdm_Dtl : SP {
			public Pr_ld_stg_prd_gdm_Dtl() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[Pr_ld_stg_prd_gdm_Dtl]";
			}
		}

		///<summary>
		/// ID: 756197744
		/// Modified: 11/16/2016 12:39:03 PM
		/// Parameters: 8
		///</summary>
		public partial class PR_MANAGE_ACTIONS : SP {
			public PR_MANAGE_ACTIONS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_ACTIONS]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 ACTN_SID {
				set { SetParmeter("ACTN_SID", value); }
				get { return (Int32)GetParameter("ACTN_SID"); }
			}

			///<summary>
			/// DataType: varchar(80)
			/// Mode: IN
			/// Max Length: 80
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 80, false)]
			public String ACTN_CD {
				set { SetParmeter("ACTN_CD", value); }
				get { return (String)GetParameter("ACTN_CD"); }
			}

			///<summary>
			/// DataType: varchar(500)
			/// Mode: IN
			/// Max Length: 500
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 500, false)]
			public String ACTN_DESC {
				set { SetParmeter("ACTN_DESC", value); }
				get { return (String)GetParameter("ACTN_DESC"); }
			}

			///<summary>
			/// DataType: varchar(80)
			/// Mode: IN
			/// Max Length: 80
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 80, false)]
			public String ACTN_CATGRY_CD {
				set { SetParmeter("ACTN_CATGRY_CD", value); }
				get { return (String)GetParameter("ACTN_CATGRY_CD"); }
			}

			///<summary>
			/// DataType: varchar(25)
			/// Mode: IN
			/// Max Length: 25
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 25, false)]
			public String WFSTG_ACTN_CD {
				set { SetParmeter("WFSTG_ACTN_CD", value); }
				get { return (String)GetParameter("WFSTG_ACTN_CD"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 0, false)]
			public Int32 SRT_ORD {
				set { SetParmeter("SRT_ORD", value); }
				get { return (Int32)GetParameter("SRT_ORD"); }
			}
		}

		///<summary>
		/// ID: 772197801
		/// Modified: 11/16/2016 8:09:26 AM
		/// Parameters: 7
		///</summary>
		public partial class PR_MANAGE_APPLICATIONS : SP {
			public PR_MANAGE_APPLICATIONS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_APPLICATIONS]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 APP_SID {
				set { SetParmeter("APP_SID", value); }
				get { return (Int32)GetParameter("APP_SID"); }
			}

			///<summary>
			/// DataType: varchar(25)
			/// Mode: IN
			/// Max Length: 25
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 25, false)]
			public String APP_CD {
				set { SetParmeter("APP_CD", value); }
				get { return (String)GetParameter("APP_CD"); }
			}

			///<summary>
			/// DataType: varchar(500)
			/// Mode: IN
			/// Max Length: 500
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 500, false)]
			public String APP_DESC {
				set { SetParmeter("APP_DESC", value); }
				get { return (String)GetParameter("APP_DESC"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 100, false)]
			public String APP_SUITE {
				set { SetParmeter("APP_SUITE", value); }
				get { return (String)GetParameter("APP_SUITE"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Boolean ACTV_IND {
				set { SetParmeter("ACTV_IND", value); }
				get { return (Boolean)GetParameter("ACTV_IND"); }
			}
		}

		///<summary>
		/// ID: 1908201848
		/// Modified: 11/8/2016 10:48:36 AM
		/// Parameters: 0
		///</summary>
		public partial class PR_MANAGE_BTCH_LD_LOG : SP {
			public PR_MANAGE_BTCH_LD_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_BTCH_LD_LOG]";
			}
		}

		///<summary>
		/// ID: 1861581670
		/// Modified: 11/15/2016 9:55:19 AM
		/// Parameters: 7
		///</summary>
		public partial class PR_MANAGE_CONSTANT_VALUES : SP {
			public PR_MANAGE_CONSTANT_VALUES() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_CONSTANT_VALUES]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: varchar(50)
			/// Mode: IN
			/// Max Length: 50
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 50, false)]
			public String cnst_nm {
				set { SetParmeter("cnst_nm", value); }
				get { return (String)GetParameter("cnst_nm"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Int32 cnst_sid {
				set { SetParmeter("cnst_sid", value); }
				get { return (Int32)GetParameter("cnst_sid"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", -1, false)]
			public String cnst_desc {
				set { SetParmeter("cnst_desc", value); }
				get { return (String)GetParameter("cnst_desc"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", -1, false)]
			public String cnst_val_txt {
				set { SetParmeter("cnst_val_txt", value); }
				get { return (String)GetParameter("cnst_val_txt"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Boolean ui_upd_flg {
				set { SetParmeter("ui_upd_flg", value); }
				get { return (Boolean)GetParameter("ui_upd_flg"); }
			}
		}

		///<summary>
		/// ID: 1124199055
		/// Modified: 11/15/2016 9:40:30 AM
		/// Parameters: 11
		///</summary>
		public partial class PR_MANAGE_DEAL_TYPES : SP {
			public PR_MANAGE_DEAL_TYPES() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_DEAL_TYPES]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 DEAL_TYPE_SID {
				set { SetParmeter("DEAL_TYPE_SID", value); }
				get { return (Int32)GetParameter("DEAL_TYPE_SID"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Int32 DEAL_ATRB_SID {
				set { SetParmeter("DEAL_ATRB_SID", value); }
				get { return (Int32)GetParameter("DEAL_ATRB_SID"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 100, false)]
			public String DEAL_TYPE_CD {
				set { SetParmeter("DEAL_TYPE_CD", value); }
				get { return (String)GetParameter("DEAL_TYPE_CD"); }
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 255, false)]
			public String DEAL_TYPE_DESC {
				set { SetParmeter("DEAL_TYPE_DESC", value); }
				get { return (String)GetParameter("DEAL_TYPE_DESC"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Int32 TEMPLT_DEAL_SID {
				set { SetParmeter("TEMPLT_DEAL_SID", value); }
				get { return (Int32)GetParameter("TEMPLT_DEAL_SID"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 0, false)]
			public Int32 TEMPLT_DEAL_NBR {
				set { SetParmeter("TEMPLT_DEAL_NBR", value); }
				get { return (Int32)GetParameter("TEMPLT_DEAL_NBR"); }
			}

			///<summary>
			/// DataType: varchar(10)
			/// Mode: IN
			/// Max Length: 10
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", 10, false)]
			public String TRKR_NBR_DT_LTR {
				set { SetParmeter("TRKR_NBR_DT_LTR", value); }
				get { return (String)GetParameter("TRKR_NBR_DT_LTR"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(10, "ParameterDirection.Input", 0, false)]
			public Boolean PERFORM_CTST {
				set { SetParmeter("PERFORM_CTST", value); }
				get { return (Boolean)GetParameter("PERFORM_CTST"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(11, "ParameterDirection.Input", 0, false)]
			public Boolean ACTV_IND {
				set { SetParmeter("ACTV_IND", value); }
				get { return (Boolean)GetParameter("ACTV_IND"); }
			}
		}

		///<summary>
		/// ID: 919674324
		/// Modified: 11/4/2016 2:57:44 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MANAGE_LOGS : SP {
			public PR_MANAGE_LOGS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_LOGS]";
			}
		}

		///<summary>
		/// ID: 1140199112
		/// Modified: 11/15/2016 9:28:51 AM
		/// Parameters: 10
		///</summary>
		public partial class PR_MANAGE_ROLE_TYPES : SP {
			public PR_MANAGE_ROLE_TYPES() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MANAGE_ROLE_TYPES]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String idsid {
				set { SetParmeter("idsid", value); }
				get { return (String)GetParameter("idsid"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 20, false)]
			public String mode {
				set { SetParmeter("mode", value); }
				get { return (String)GetParameter("mode"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 ROLE_TYPE_SID {
				set { SetParmeter("ROLE_TYPE_SID", value); }
				get { return (Int32)GetParameter("ROLE_TYPE_SID"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Int32 APP_SID {
				set { SetParmeter("APP_SID", value); }
				get { return (Int32)GetParameter("APP_SID"); }
			}

			///<summary>
			/// DataType: varchar(25)
			/// Mode: IN
			/// Max Length: 25
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 25, false)]
			public String ROLE_TYPE_CD {
				set { SetParmeter("ROLE_TYPE_CD", value); }
				get { return (String)GetParameter("ROLE_TYPE_CD"); }
			}

			///<summary>
			/// DataType: varchar(80)
			/// Mode: IN
			/// Max Length: 80
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 80, false)]
			public String ROLE_TYPE_DSPLY_CD {
				set { SetParmeter("ROLE_TYPE_DSPLY_CD", value); }
				get { return (String)GetParameter("ROLE_TYPE_DSPLY_CD"); }
			}

			///<summary>
			/// DataType: varchar(500)
			/// Mode: IN
			/// Max Length: 500
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 500, false)]
			public String ROLE_TYPE_DESC {
				set { SetParmeter("ROLE_TYPE_DESC", value); }
				get { return (String)GetParameter("ROLE_TYPE_DESC"); }
			}

			///<summary>
			/// DataType: varchar(25)
			/// Mode: IN
			/// Max Length: 25
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 25, false)]
			public String ROLE_TIER_CD {
				set { SetParmeter("ROLE_TIER_CD", value); }
				get { return (String)GetParameter("ROLE_TIER_CD"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", 0, false)]
			public Boolean IS_SNGL_SLCT {
				set { SetParmeter("IS_SNGL_SLCT", value); }
				get { return (Boolean)GetParameter("IS_SNGL_SLCT"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(10, "ParameterDirection.Input", 0, false)]
			public Boolean ACTV_IND {
				set { SetParmeter("ACTV_IND", value); }
				get { return (Boolean)GetParameter("ACTV_IND"); }
			}
		}

		///<summary>
		/// ID: 798625888
		/// Modified: 11/1/2016 1:44:17 PM
		/// Parameters: 2
		///</summary>
		public partial class PR_MSG : SP {
			public PR_MSG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MSG]";
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String MSG {
				set { SetParmeter("MSG", value); }
				get { return (String)GetParameter("MSG"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 MODE {
				set { SetParmeter("MODE", value); }
				get { return (Int32)GetParameter("MODE"); }
			}
		}

		///<summary>
		/// ID: 1273771595
		/// Modified: 11/22/2016 8:47:05 PM
		/// Parameters: 4
		///</summary>
		public partial class PR_MYDL_GET_CUST_CLNDR_QTR : SP {
			public PR_MYDL_GET_CUST_CLNDR_QTR() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_GET_CUST_CLNDR_QTR]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 CUST_MBR_SID {
				set { SetParmeter("CUST_MBR_SID", value); }
				get { return (Int32)GetParameter("CUST_MBR_SID"); }
			}

			///<summary>
			/// DataType: smallint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int16 YR_NBR {
				set { SetParmeter("YR_NBR", value); }
				get { return (Int16)GetParameter("YR_NBR"); }
			}

			///<summary>
			/// DataType: smallint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int16 QTR_NBR {
				set { SetParmeter("QTR_NBR", value); }
				get { return (Int16)GetParameter("QTR_NBR"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public DateTime DTM {
				set { SetParmeter("DTM", value); }
				get { return (DateTime)GetParameter("DTM"); }
			}
		}

		///<summary>
		/// ID: 925246351
		/// Modified: 11/21/2016 12:26:11 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_GET_CUST_DIV : SP {
			public PR_MYDL_GET_CUST_DIV() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_GET_CUST_DIV]";
			}
		}

		///<summary>
		/// ID: 1197247320
		/// Modified: 11/17/2016 3:02:39 AM
		/// Parameters: 4
		///</summary>
		public partial class PR_MYDL_GET_MY_CUST : SP {
			public PR_MYDL_GET_MY_CUST() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_GET_MY_CUST]";
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 20, false)]
			public String IN_IDSID {
				set { SetParmeter("IN_IDSID", value); }
				get { return (String)GetParameter("IN_IDSID"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean IN_FULL_ACCS_FLG {
				set { SetParmeter("IN_FULL_ACCS_FLG", value); }
				get { return (Boolean)GetParameter("IN_FULL_ACCS_FLG"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Boolean IN_ALL_CUST_FLG {
				set { SetParmeter("IN_ALL_CUST_FLG", value); }
				get { return (Boolean)GetParameter("IN_ALL_CUST_FLG"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 0, false)]
			public Int32 IN_CUST_MBR_SID {
				set { SetParmeter("IN_CUST_MBR_SID", value); }
				get { return (Int32)GetParameter("IN_CUST_MBR_SID"); }
			}
		}

		///<summary>
		/// ID: 118291481
		/// Modified: 11/27/2016 11:45:41 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_MYDL_LD_DIM_GEO : SP {
			public PR_MYDL_LD_DIM_GEO() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_DIM_GEO]";
			}

			///<summary>
			/// DataType: char(1)
			/// Mode: IN
			/// Max Length: 1
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 1, false)]
			public String in_add_denorm_prc_call {
				set { SetParmeter("in_add_denorm_prc_call", value); }
				get { return (String)GetParameter("in_add_denorm_prc_call"); }
			}
		}

		///<summary>
		/// ID: 2036202304
		/// Modified: 11/21/2016 3:33:00 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_EDW_CUST_DTL : SP {
			public PR_MYDL_LD_STG_EDW_CUST_DTL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_EDW_CUST_DTL]";
			}
		}

		///<summary>
		/// ID: 1460200252
		/// Modified: 11/14/2016 1:46:39 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_EDW_PRD_DTL : SP {
			public PR_MYDL_LD_STG_EDW_PRD_DTL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_EDW_PRD_DTL]";
			}
		}

		///<summary>
		/// ID: 1616724812
		/// Modified: 11/28/2016 11:37:47 AM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_GDM_CUST_DTL : SP {
			public PR_MYDL_LD_STG_GDM_CUST_DTL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_GDM_CUST_DTL]";
			}
		}

		///<summary>
		/// ID: 1508200423
		/// Modified: 11/27/2016 10:27:42 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_GDM_GEO : SP {
			public PR_MYDL_LD_STG_GDM_GEO() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_GDM_GEO]";
			}
		}

		///<summary>
		/// ID: 1700201107
		/// Modified: 11/14/2016 1:50:31 PM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_GDM_PRD_DTL : SP {
			public PR_MYDL_LD_STG_GDM_PRD_DTL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_GDM_PRD_DTL]";
			}
		}

		///<summary>
		/// ID: 1129771082
		/// Modified: 11/22/2016 2:02:39 AM
		/// Parameters: 0
		///</summary>
		public partial class PR_MYDL_LD_STG_HRCDS_EMP_DTL : SP {
			public PR_MYDL_LD_STG_HRCDS_EMP_DTL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_MYDL_LD_STG_HRCDS_EMP_DTL]";
			}
		}

		///<summary>
		/// ID: 613577224
		/// Modified: 11/7/2016 9:56:47 AM
		/// Parameters: 0
		///</summary>
		public partial class PR_PING_DB : SP {
			public PR_PING_DB() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_PING_DB]";
			}
		}

		///<summary>
		/// ID: 1632724869
		/// Modified: 11/10/2016 3:43:52 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_PRINT : SP {
			public PR_PRINT() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_PRINT]";
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", -1, false)]
			public String txt {
				set { SetParmeter("txt", value); }
				get { return (String)GetParameter("txt"); }
			}
		}

		///<summary>
		/// ID: 1570104634
		/// Modified: 10/28/2016 10:58:50 AM
		/// Parameters: 2
		///</summary>
		public partial class PR_REAPPLY_OBJ_PERM : SP {
			public PR_REAPPLY_OBJ_PERM() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_REAPPLY_OBJ_PERM]";
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String db_nm_to_exec {
				set { SetParmeter("db_nm_to_exec", value); }
				get { return (String)GetParameter("db_nm_to_exec"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Boolean debug {
				set { SetParmeter("debug", value); }
				get { return (Boolean)GetParameter("debug"); }
			}
		}

		///<summary>
		/// ID: 1586104691
		/// Modified: 11/2/2016 12:42:37 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_REFRESH_VIEWS : SP {
			public PR_REFRESH_VIEWS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_REFRESH_VIEWS]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 NestLevel {
				set { SetParmeter("NestLevel", value); }
				get { return (Int32)GetParameter("NestLevel"); }
			}
		}

		///<summary>
		/// ID: 1166627199
		/// Modified: 11/1/2016 2:29:12 PM
		/// Parameters: 3
		///</summary>
		public partial class PR_REORG_IDX : SP {
			public PR_REORG_IDX() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_REORG_IDX]";
			}

			///<summary>
			/// DataType: decimal
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Decimal FragReorgLimitPct {
				set { SetParmeter("FragReorgLimitPct", value); }
				get { return (Decimal)GetParameter("FragReorgLimitPct"); }
			}

			///<summary>
			/// DataType: decimal
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Decimal FragRebuildLimitPct {
				set { SetParmeter("FragRebuildLimitPct", value); }
				get { return (Decimal)GetParameter("FragRebuildLimitPct"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Boolean SortInTempDB {
				set { SetParmeter("SortInTempDB", value); }
				get { return (Boolean)GetParameter("SortInTempDB"); }
			}
		}

		///<summary>
		/// ID: 22291139
		/// Modified: 11/24/2016 8:41:20 AM
		/// Parameters: 8
		///</summary>
		public partial class PR_SEND_ATTCH_EMAIL : SP {
			public PR_SEND_ATTCH_EMAIL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SEND_ATTCH_EMAIL]";
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 100, false)]
			public String v_name {
				set { SetParmeter("v_name", value); }
				get { return (String)GetParameter("v_name"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 v_iss_cnt {
				set { SetParmeter("v_iss_cnt", value); }
				get { return (Int32)GetParameter("v_iss_cnt"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 v_tot_cnt {
				set { SetParmeter("v_tot_cnt", value); }
				get { return (Int32)GetParameter("v_tot_cnt"); }
			}

			///<summary>
			/// DataType: varchar(1000)
			/// Mode: IN
			/// Max Length: 1000
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 1000, false)]
			public String v_email_addr {
				set { SetParmeter("v_email_addr", value); }
				get { return (String)GetParameter("v_email_addr"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 100, false)]
			public String v_use_case_cd {
				set { SetParmeter("v_use_case_cd", value); }
				get { return (String)GetParameter("v_use_case_cd"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 0, false)]
			public Int32 v_exec_id {
				set { SetParmeter("v_exec_id", value); }
				get { return (Int32)GetParameter("v_exec_id"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", -1, false)]
			public String v_customsummaryemailmessage {
				set { SetParmeter("v_customsummaryemailmessage", value); }
				get { return (String)GetParameter("v_customsummaryemailmessage"); }
			}

			///<summary>
			/// DataType: char(1)
			/// Mode: IN
			/// Max Length: 1
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 1, false)]
			public String l_send_cont_flag {
				set { SetParmeter("l_send_cont_flag", value); }
				get { return (String)GetParameter("l_send_cont_flag"); }
			}
		}

		///<summary>
		/// ID: 1182627256
		/// Modified: 11/1/2016 2:48:58 PM
		/// Parameters: 4
		///</summary>
		public partial class PR_SEND_MAIL : SP {
			public PR_SEND_MAIL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SEND_MAIL]";
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 100, false)]
			public String CNST_NM {
				set { SetParmeter("CNST_NM", value); }
				get { return (String)GetParameter("CNST_NM"); }
			}

			///<summary>
			/// DataType: varchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String SUBJECT {
				set { SetParmeter("SUBJECT", value); }
				get { return (String)GetParameter("SUBJECT"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", -1, false)]
			public String BODY {
				set { SetParmeter("BODY", value); }
				get { return (String)GetParameter("BODY"); }
			}

			///<summary>
			/// DataType: varchar(4)
			/// Mode: IN
			/// Max Length: 4
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 4, false)]
			public String FORMAT {
				set { SetParmeter("FORMAT", value); }
				get { return (String)GetParameter("FORMAT"); }
			}
		}

		///<summary>
		/// ID: 1602104748
		/// Modified: 10/28/2016 2:00:40 PM
		/// Parameters: 9
		///</summary>
		public partial class PR_SET_OBJ_PERM : SP {
			public PR_SET_OBJ_PERM() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SET_OBJ_PERM]";
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String db_nm {
				set { SetParmeter("db_nm", value); }
				get { return (String)GetParameter("db_nm"); }
			}

			///<summary>
			/// DataType: nvarchar(2000)
			/// Mode: IN
			/// Max Length: 2000
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 2000, false)]
			public String obj_nm {
				set { SetParmeter("obj_nm", value); }
				get { return (String)GetParameter("obj_nm"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 100, false)]
			public String actn_state {
				set { SetParmeter("actn_state", value); }
				get { return (String)GetParameter("actn_state"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 100, false)]
			public String actn_type {
				set { SetParmeter("actn_type", value); }
				get { return (String)GetParameter("actn_type"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 100, false)]
			public String login_nm {
				set { SetParmeter("login_nm", value); }
				get { return (String)GetParameter("login_nm"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 100, false)]
			public String db_role {
				set { SetParmeter("db_role", value); }
				get { return (String)GetParameter("db_role"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 100, false)]
			public String col_nm {
				set { SetParmeter("col_nm", value); }
				get { return (String)GetParameter("col_nm"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 0, false)]
			public Boolean debug {
				set { SetParmeter("debug", value); }
				get { return (Boolean)GetParameter("debug"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", 100, false)]
			public String csl_env {
				set { SetParmeter("csl_env", value); }
				get { return (String)GetParameter("csl_env"); }
			}
		}

		///<summary>
		/// ID: 1205579333
		/// Modified: 10/8/2016 9:58:42 PM
		/// Parameters: 3
		///</summary>
		public partial class PR_SET_POC_EMP : SP {
			public PR_SET_POC_EMP() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SET_POC_EMP]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 emp_sid {
				set { SetParmeter("emp_sid", value); }
				get { return (Int32)GetParameter("emp_sid"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 100, false)]
			public String first_nm {
				set { SetParmeter("first_nm", value); }
				get { return (String)GetParameter("first_nm"); }
			}

			///<summary>
			/// DataType: varchar(100)
			/// Mode: IN
			/// Max Length: 100
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 100, false)]
			public String last_nm {
				set { SetParmeter("last_nm", value); }
				get { return (String)GetParameter("last_nm"); }
			}
		}

		///<summary>
		/// ID: 1193771310
		/// Modified: 11/28/2016 12:26:44 AM
		/// Parameters: 9
		///</summary>
		public partial class PR_SQL_DB_MAIL : SP {
			public PR_SQL_DB_MAIL() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_SQL_DB_MAIL]";
			}

			///<summary>
			/// DataType: nvarchar(1000)
			/// Mode: IN
			/// Max Length: 1000
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 1000, false)]
			public String from_user_email {
				set { SetParmeter("from_user_email", value); }
				get { return (String)GetParameter("from_user_email"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", -1, false)]
			public String to_user_email {
				set { SetParmeter("to_user_email", value); }
				get { return (String)GetParameter("to_user_email"); }
			}

			///<summary>
			/// DataType: nvarchar(1000)
			/// Mode: IN
			/// Max Length: 1000
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 1000, false)]
			public String subject {
				set { SetParmeter("subject", value); }
				get { return (String)GetParameter("subject"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", -1, false)]
			public String message {
				set { SetParmeter("message", value); }
				get { return (String)GetParameter("message"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", -1, false)]
			public String dce_cc_list {
				set { SetParmeter("dce_cc_list", value); }
				get { return (String)GetParameter("dce_cc_list"); }
			}

			///<summary>
			/// DataType: nvarchar(1000)
			/// Mode: IN
			/// Max Length: 1000
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 1000, false)]
			public String priority {
				set { SetParmeter("priority", value); }
				get { return (String)GetParameter("priority"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", -1, false)]
			public String attachment {
				set { SetParmeter("attachment", value); }
				get { return (String)GetParameter("attachment"); }
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 255, false)]
			public String query_attachment_filename {
				set { SetParmeter("query_attachment_filename", value); }
				get { return (String)GetParameter("query_attachment_filename"); }
			}

			///<summary>
			/// DataType: nvarchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", -1, false)]
			public String dce_bcc_list {
				set { SetParmeter("dce_bcc_list", value); }
				get { return (String)GetParameter("dce_bcc_list"); }
			}
		}

		///<summary>
		/// ID: 644197345
		/// Modified: 11/4/2016 9:00:01 AM
		/// Parameters: 5
		///</summary>
		public partial class PR_UPD_BTCH_LD_LOG : SP {
			public PR_UPD_BTCH_LD_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_UPD_BTCH_LD_LOG]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 IN_JOB_SID {
				set { SetParmeter("IN_JOB_SID", value); }
				get { return (Int32)GetParameter("IN_JOB_SID"); }
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 255, false)]
			public String IN_PKG_NM {
				set { SetParmeter("IN_PKG_NM", value); }
				get { return (String)GetParameter("IN_PKG_NM"); }
			}

			///<summary>
			/// DataType: varchar(255)
			/// Mode: IN
			/// Max Length: 255
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 255, false)]
			public String IN_RUN_STS {
				set { SetParmeter("IN_RUN_STS", value); }
				get { return (String)GetParameter("IN_RUN_STS"); }
			}

			///<summary>
			/// DataType: varchar(20)
			/// Mode: IN
			/// Max Length: 20
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 20, false)]
			public String IN_DB_NM {
				set { SetParmeter("IN_DB_NM", value); }
				get { return (String)GetParameter("IN_DB_NM"); }
			}

			///<summary>
			/// DataType: varchar(500)
			/// Mode: IN
			/// Max Length: 500
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 500, false)]
			public String IN_ERR_MSG {
				set { SetParmeter("IN_ERR_MSG", value); }
				get { return (String)GetParameter("IN_ERR_MSG"); }
			}
		}

		///<summary>
		/// ID: 951674438
		/// Modified: 11/14/2016 8:58:46 AM
		/// Parameters: 5
		///</summary>
		public partial class PR_UPD_DB_LOG : SP {
			public PR_UPD_DB_LOG() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_UPD_DB_LOG]";
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Int32 in_log_sid {
				set { SetParmeter("in_log_sid", value); }
				get { return (Int32)GetParameter("in_log_sid"); }
			}

			///<summary>
			/// DataType: datetime
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public DateTime in_end_tm {
				set { SetParmeter("in_end_tm", value); }
				get { return (DateTime)GetParameter("in_end_tm"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 in_recrd_cnt {
				set { SetParmeter("in_recrd_cnt", value); }
				get { return (Int32)GetParameter("in_recrd_cnt"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", -1, false)]
			public String in_err_msg {
				set { SetParmeter("in_err_msg", value); }
				get { return (String)GetParameter("in_err_msg"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 0, false)]
			public Int32 in_wwid {
				set { SetParmeter("in_wwid", value); }
				get { return (Int32)GetParameter("in_wwid"); }
			}
		}

		///<summary>
		/// ID: 1198627313
		/// Modified: 11/1/2016 8:04:51 PM
		/// Parameters: 1
		///</summary>
		public partial class PR_UPD_STATS : SP {
			public PR_UPD_STATS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_UPD_STATS]";
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Boolean display_stats {
				set { SetParmeter("display_stats", value); }
				get { return (Boolean)GetParameter("display_stats"); }
			}
		}

		///<summary>
		/// ID: 1214627370
		/// Modified: 11/1/2016 8:24:24 PM
		/// Parameters: 3
		///</summary>
		public partial class PR_UTIL_LOG_STATS : SP {
			public PR_UTIL_LOG_STATS() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_UTIL_LOG_STATS]";
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 0, false)]
			public Boolean b_return_new {
				set { SetParmeter("b_return_new", value); }
				get { return (Boolean)GetParameter("b_return_new"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 0, false)]
			public Int32 rolling_delete_days {
				set { SetParmeter("rolling_delete_days", value); }
				get { return (Int32)GetParameter("rolling_delete_days"); }
			}

			///<summary>
			/// DataType: int
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 0, false)]
			public Int32 abort_log_cutoff_interval_seconds {
				set { SetParmeter("abort_log_cutoff_interval_seconds", value); }
				get { return (Int32)GetParameter("abort_log_cutoff_interval_seconds"); }
			}
		}

		///<summary>
		/// ID: 1454628225
		/// Modified: 11/2/2016 1:45:16 PM
		/// Parameters: 24
		///</summary>
		public partial class PR_WhoIsActive : SP {
			public PR_WhoIsActive() {
				DatabaseName = "";
				StoredProdedureName = "[dbo].[PR_WhoIsActive]";
				OutputParameterCount = 1;
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(1, "ParameterDirection.Input", 128, false)]
			public String filter {
				set { SetParmeter("filter", value); }
				get { return (String)GetParameter("filter"); }
			}

			///<summary>
			/// DataType: varchar(10)
			/// Mode: IN
			/// Max Length: 10
			///</summary>
			[SQLParameterAttribute(2, "ParameterDirection.Input", 10, false)]
			public String filter_type {
				set { SetParmeter("filter_type", value); }
				get { return (String)GetParameter("filter_type"); }
			}

			///<summary>
			/// DataType: nvarchar(128)
			/// Mode: IN
			/// Max Length: 128
			///</summary>
			[SQLParameterAttribute(3, "ParameterDirection.Input", 128, false)]
			public String not_filter {
				set { SetParmeter("not_filter", value); }
				get { return (String)GetParameter("not_filter"); }
			}

			///<summary>
			/// DataType: varchar(10)
			/// Mode: IN
			/// Max Length: 10
			///</summary>
			[SQLParameterAttribute(4, "ParameterDirection.Input", 10, false)]
			public String not_filter_type {
				set { SetParmeter("not_filter_type", value); }
				get { return (String)GetParameter("not_filter_type"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(5, "ParameterDirection.Input", 0, false)]
			public Boolean show_own_spid {
				set { SetParmeter("show_own_spid", value); }
				get { return (Boolean)GetParameter("show_own_spid"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(6, "ParameterDirection.Input", 0, false)]
			public Boolean show_system_spids {
				set { SetParmeter("show_system_spids", value); }
				get { return (Boolean)GetParameter("show_system_spids"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(7, "ParameterDirection.Input", 0, false)]
			public Int32 show_sleeping_spids {
				set { SetParmeter("show_sleeping_spids", value); }
				get { return (Int32)GetParameter("show_sleeping_spids"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(8, "ParameterDirection.Input", 0, false)]
			public Boolean get_full_inner_text {
				set { SetParmeter("get_full_inner_text", value); }
				get { return (Boolean)GetParameter("get_full_inner_text"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(9, "ParameterDirection.Input", 0, false)]
			public Int32 get_plans {
				set { SetParmeter("get_plans", value); }
				get { return (Int32)GetParameter("get_plans"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(10, "ParameterDirection.Input", 0, false)]
			public Boolean get_outer_command {
				set { SetParmeter("get_outer_command", value); }
				get { return (Boolean)GetParameter("get_outer_command"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(11, "ParameterDirection.Input", 0, false)]
			public Boolean get_transaction_info {
				set { SetParmeter("get_transaction_info", value); }
				get { return (Boolean)GetParameter("get_transaction_info"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(12, "ParameterDirection.Input", 0, false)]
			public Int32 get_task_info {
				set { SetParmeter("get_task_info", value); }
				get { return (Int32)GetParameter("get_task_info"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(13, "ParameterDirection.Input", 0, false)]
			public Boolean get_locks {
				set { SetParmeter("get_locks", value); }
				get { return (Boolean)GetParameter("get_locks"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(14, "ParameterDirection.Input", 0, false)]
			public Boolean get_avg_time {
				set { SetParmeter("get_avg_time", value); }
				get { return (Boolean)GetParameter("get_avg_time"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(15, "ParameterDirection.Input", 0, false)]
			public Boolean get_additional_info {
				set { SetParmeter("get_additional_info", value); }
				get { return (Boolean)GetParameter("get_additional_info"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(16, "ParameterDirection.Input", 0, false)]
			public Boolean find_block_leaders {
				set { SetParmeter("find_block_leaders", value); }
				get { return (Boolean)GetParameter("find_block_leaders"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(17, "ParameterDirection.Input", 0, false)]
			public Int32 delta_interval {
				set { SetParmeter("delta_interval", value); }
				get { return (Int32)GetParameter("delta_interval"); }
			}

			///<summary>
			/// DataType: varchar(8000)
			/// Mode: IN
			/// Max Length: 8000
			///</summary>
			[SQLParameterAttribute(18, "ParameterDirection.Input", 8000, false)]
			public String output_column_list {
				set { SetParmeter("output_column_list", value); }
				get { return (String)GetParameter("output_column_list"); }
			}

			///<summary>
			/// DataType: varchar(500)
			/// Mode: IN
			/// Max Length: 500
			///</summary>
			[SQLParameterAttribute(19, "ParameterDirection.Input", 500, false)]
			public String sort_order {
				set { SetParmeter("sort_order", value); }
				get { return (String)GetParameter("sort_order"); }
			}

			///<summary>
			/// DataType: tinyint
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(20, "ParameterDirection.Input", 0, false)]
			public Int32 format_output {
				set { SetParmeter("format_output", value); }
				get { return (Int32)GetParameter("format_output"); }
			}

			///<summary>
			/// DataType: varchar(4000)
			/// Mode: IN
			/// Max Length: 4000
			///</summary>
			[SQLParameterAttribute(21, "ParameterDirection.Input", 4000, false)]
			public String destination_table {
				set { SetParmeter("destination_table", value); }
				get { return (String)GetParameter("destination_table"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(22, "ParameterDirection.Input", 0, false)]
			public Boolean return_schema {
				set { SetParmeter("return_schema", value); }
				get { return (Boolean)GetParameter("return_schema"); }
			}

			///<summary>
			/// DataType: varchar
			/// Mode: INOUT
			///</summary>
			[SQLParameterAttribute(23, "ParameterDirection.InputOutput", -1, false)]
			public String schema {
				set { SetParmeter("schema", value); }
				get { return (String)GetParameter("schema"); }
			}

			///<summary>
			/// DataType: bit
			/// Mode: IN
			///</summary>
			[SQLParameterAttribute(24, "ParameterDirection.Input", 0, false)]
			public Boolean help {
				set { SetParmeter("help", value); }
				get { return (Boolean)GetParameter("help"); }
			}
		}
	}


}

