
/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 5/12/2014 10:22:11 AM
Database Connection: VMSDDDM001\CP1CIAS,3181, CDMS
Machine Name: BJOSS-MOBL
User: AMR\bjoss
*/

//TODO - DSDealBase1.generated.cs - Import the original TT file and create this as needed.  This is just hard coded for now until DB is in better shape.
using System;
using System.Data;

namespace Intel.MyDeals.DataAccessLib
{
    public partial class DSDealBase : DataSet
    {
        public DSDealBase()
        {

            this.Tables.Add(new DTDeal());
            this.Tables.Add(new DTData());
            base.AcceptChanges();

        }
    }


    [SerializableAttribute]
    public partial class DTDeal : DataTable
    {

        public DTDeal()
        {

            this.TableName = "STG_CDMS_DEAL_WF_DEAL";

            this.Columns.Add("BTCH_ID", typeof(Guid));
            this.Columns.Add("DEAL_ID", typeof(Int32));
            this.Columns.Add("DEAL_NBR", typeof(Int32));
            this.Columns.Add("BYPASS_REDEAL", typeof(Boolean));
            this.Columns.Add("IN_PROCESS", typeof(Boolean));
            this.Columns.Add("RETURN_POSITIVE", typeof(Boolean));
            this.Columns.Add("RETURN_SAVE", typeof(Boolean));
            this.Columns.Add("DEAL_SAVE", typeof(Boolean));
            this.Columns.Add("STAGE", typeof(String));
            this.Columns.Add("WORKFLOW", typeof(String));
            this.Columns.Add("DEAL_ACTION", typeof(String));

            this.AcceptChanges();

        }

        protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
        {
            return new DRDeal(builder);
        }

        public const string DB_TABLE_NAME = "STG_CDMS_DEAL_WF_DEAL";

        public struct ColDex
        {
            public const int BTCH_ID = 0;
            public const int DEAL_ID = 1;
            public const int DEAL_NBR = 2;
            public const int BYPASS_REDEAL = 3;
            public const int IN_PROCESS = 4;
            public const int RETURN_POSITIVE = 5;
            public const int RETURN_SAVE = 6;
            public const int DEAL_SAVE = 7;
            public const int STAGE = 8;
            public const int WORKFLOW = 9;
            public const int DEAL_ACTION = 10;
        }

        public struct ColNm
        {
            public const string BTCH_ID = "BTCH_ID";
            public const string DEAL_ID = "DEAL_ID";
            public const string DEAL_NBR = "DEAL_NBR";
            public const string BYPASS_REDEAL = "BYPASS_REDEAL";
            public const string IN_PROCESS = "IN_PROCESS";
            public const string RETURN_POSITIVE = "RETURN_POSITIVE";
            public const string RETURN_SAVE = "RETURN_SAVE";
            public const string DEAL_SAVE = "DEAL_SAVE";
            public const string STAGE = "STAGE";
            public const string WORKFLOW = "WORKFLOW";
            public const string DEAL_ACTION = "DEAL_ACTION";
        }

    }


    public partial class DTData : DataTable
    {

        public DTData()
        {

            this.TableName = "STG_CDMS_DEAL_WF_DATA";

            this.Columns.Add("BTCH_ID", typeof(Guid));
            this.Columns.Add("SRC_CD", typeof(String));
            this.Columns.Add("DATA_TEXT", typeof(String));
            this.Columns.Add("ATRB_SID", typeof(Int32));
            this.Columns.Add("DEAL_ID", typeof(Int32));
            this.Columns.Add("DEAL_NBR", typeof(Int32));
            this.Columns.Add("GEO_MBR_SID", typeof(Int32));
            this.Columns.Add("PRD_MBR_SID", typeof(Int32));
            this.Columns.Add("SEG_MBR_SID", typeof(Int32));
            this.Columns.Add("LAYER1_SID", typeof(Int32));
            this.Columns.Add("LAYER2_SID", typeof(Int32));
            this.Columns.Add("LAYER3_SID", typeof(Int32));
            this.Columns.Add("LAYER4_SID", typeof(Int32));
            this.Columns.Add("LAYER5_SID", typeof(Int32));
            this.Columns.Add("ATRB_VAL", typeof(String));

            this.AcceptChanges();

        }

        protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
        {
            return new DRData(builder);
        }

        public const string DB_TABLE_NAME = "STG_CDMS_DEAL_WF_DATA";

        public struct ColDex
        {
            public const int BTCH_ID = 0;
            public const int SRC_CD = 1;
            public const int DATA_TEXT = 2;
            public const int ATRB_SID = 3;
            public const int DEAL_ID = 4;
            public const int DEAL_NBR = 5;
            public const int GEO_MBR_SID = 6;
            public const int PRD_MBR_SID = 7;
            public const int SEG_MBR_SID = 8;
            public const int LAYER1_SID = 9;
            public const int LAYER2_SID = 10;
            public const int LAYER3_SID = 11;
            public const int LAYER4_SID = 12;
            public const int LAYER5_SID = 13;
            public const int ATRB_VAL = 14;
        }

        public struct ColNm
        {
            public const string BTCH_ID = "BTCH_ID";
            public const string SRC_CD = "SRC_CD";
            public const string DATA_TEXT = "DATA_TEXT";
            public const string ATRB_SID = "ATRB_SID";
            public const string DEAL_ID = "DEAL_ID";
            public const string DEAL_NBR = "DEAL_NBR";
            public const string GEO_MBR_SID = "GEO_MBR_SID";
            public const string PRD_MBR_SID = "PRD_MBR_SID";
            public const string SEG_MBR_SID = "SEG_MBR_SID";
            public const string LAYER1_SID = "LAYER1_SID";
            public const string LAYER2_SID = "LAYER2_SID";
            public const string LAYER3_SID = "LAYER3_SID";
            public const string LAYER4_SID = "LAYER4_SID";
            public const string LAYER5_SID = "LAYER5_SID";
            public const string ATRB_VAL = "ATRB_VAL";
        }

    }

    public partial class DRDeal : DataRow
    {

        public DRDeal(DataRowBuilder builder) : base(builder) { }


        public Guid BTCH_ID
        {
            get
            {
                if (base.IsNull("BTCH_ID")) { return default(Guid); }
                return (Guid)base["BTCH_ID"];
            }
            set
            {
                base["BTCH_ID"] = value;
            }
        }

        public Nullable<Int32> DEAL_ID
        {
            get
            {
                if (base.IsNull("DEAL_ID")) { return null; }
                return (Nullable<Int32>)base["DEAL_ID"];
            }
            set
            {
                if (value == null)
                {
                    base["DEAL_ID"] = DBNull.Value;
                }
                else
                {
                    base["DEAL_ID"] = value;
                }
            }
        }

        public Nullable<Int32> DEAL_NBR
        {
            get
            {
                if (base.IsNull("DEAL_NBR")) { return null; }
                return (Nullable<Int32>)base["DEAL_NBR"];
            }
            set
            {
                if (value == null)
                {
                    base["DEAL_NBR"] = DBNull.Value;
                }
                else
                {
                    base["DEAL_NBR"] = value;
                }
            }
        }

        public Nullable<Boolean> BYPASS_REDEAL
        {
            get
            {
                if (base.IsNull("BYPASS_REDEAL")) { return null; }
                return (Nullable<Boolean>)base["BYPASS_REDEAL"];
            }
            set
            {
                if (value == null)
                {
                    base["BYPASS_REDEAL"] = DBNull.Value;
                }
                else
                {
                    base["BYPASS_REDEAL"] = value;
                }
            }
        }

        public Nullable<Boolean> IN_PROCESS
        {
            get
            {
                if (base.IsNull("IN_PROCESS")) { return null; }
                return (Nullable<Boolean>)base["IN_PROCESS"];
            }
            set
            {
                if (value == null)
                {
                    base["IN_PROCESS"] = DBNull.Value;
                }
                else
                {
                    base["IN_PROCESS"] = value;
                }
            }
        }

        public Nullable<Boolean> RETURN_POSITIVE
        {
            get
            {
                if (base.IsNull("RETURN_POSITIVE")) { return null; }
                return (Nullable<Boolean>)base["RETURN_POSITIVE"];
            }
            set
            {
                if (value == null)
                {
                    base["RETURN_POSITIVE"] = DBNull.Value;
                }
                else
                {
                    base["RETURN_POSITIVE"] = value;
                }
            }
        }

        public Nullable<Boolean> RETURN_SAVE
        {
            get
            {
                if (base.IsNull("RETURN_SAVE")) { return null; }
                return (Nullable<Boolean>)base["RETURN_SAVE"];
            }
            set
            {
                if (value == null)
                {
                    base["RETURN_SAVE"] = DBNull.Value;
                }
                else
                {
                    base["RETURN_SAVE"] = value;
                }
            }
        }

        public Nullable<Boolean> DEAL_SAVE
        {
            get
            {
                if (base.IsNull("DEAL_SAVE")) { return null; }
                return (Nullable<Boolean>)base["DEAL_SAVE"];
            }
            set
            {
                if (value == null)
                {
                    base["DEAL_SAVE"] = DBNull.Value;
                }
                else
                {
                    base["DEAL_SAVE"] = value;
                }
            }
        }

        public String STAGE
        {
            get
            {
                if (base.IsNull("STAGE")) { return default(String); }
                return (String)base["STAGE"];
            }
            set
            {
                base["STAGE"] = value;
            }
        }

        public String WORKFLOW
        {
            get
            {
                if (base.IsNull("WORKFLOW")) { return default(String); }
                return (String)base["WORKFLOW"];
            }
            set
            {
                base["WORKFLOW"] = value;
            }
        }

        public String DEAL_ACTION
        {
            get
            {
                if (base.IsNull("DEAL_ACTION")) { return default(String); }
                return (String)base["DEAL_ACTION"];
            }
            set
            {
                base["DEAL_ACTION"] = value;
            }
        }

    }

    public partial class DRData : DataRow
    {

        public DRData(DataRowBuilder builder) : base(builder) { }


        public Guid BTCH_ID
        {
            get
            {
                if (base.IsNull("BTCH_ID")) { return default(Guid); }
                return (Guid)base["BTCH_ID"];
            }
            set
            {
                base["BTCH_ID"] = value;
            }
        }

        public String SRC_CD
        {
            get
            {
                if (base.IsNull("SRC_CD")) { return default(String); }
                return (String)base["SRC_CD"];
            }
            set
            {
                base["SRC_CD"] = value;
            }
        }

        public String DATA_TEXT
        {
            get
            {
                if (base.IsNull("DATA_TEXT")) { return default(String); }
                return (String)base["DATA_TEXT"];
            }
            set
            {
                base["DATA_TEXT"] = value;
            }
        }

        public Nullable<Int32> ATRB_SID
        {
            get
            {
                if (base.IsNull("ATRB_SID")) { return null; }
                return (Nullable<Int32>)base["ATRB_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["ATRB_SID"] = DBNull.Value;
                }
                else
                {
                    base["ATRB_SID"] = value;
                }
            }
        }

        public Nullable<Int32> DEAL_ID
        {
            get
            {
                if (base.IsNull("DEAL_ID")) { return null; }
                return (Nullable<Int32>)base["DEAL_ID"];
            }
            set
            {
                if (value == null)
                {
                    base["DEAL_ID"] = DBNull.Value;
                }
                else
                {
                    base["DEAL_ID"] = value;
                }
            }
        }

        public Nullable<Int32> DEAL_NBR
        {
            get
            {
                if (base.IsNull("DEAL_NBR")) { return null; }
                return (Nullable<Int32>)base["DEAL_NBR"];
            }
            set
            {
                if (value == null)
                {
                    base["DEAL_NBR"] = DBNull.Value;
                }
                else
                {
                    base["DEAL_NBR"] = value;
                }
            }
        }

        public Nullable<Int32> GEO_MBR_SID
        {
            get
            {
                if (base.IsNull("GEO_MBR_SID")) { return null; }
                return (Nullable<Int32>)base["GEO_MBR_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["GEO_MBR_SID"] = DBNull.Value;
                }
                else
                {
                    base["GEO_MBR_SID"] = value;
                }
            }
        }

        public Nullable<Int32> PRD_MBR_SID
        {
            get
            {
                if (base.IsNull("PRD_MBR_SID")) { return null; }
                return (Nullable<Int32>)base["PRD_MBR_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["PRD_MBR_SID"] = DBNull.Value;
                }
                else
                {
                    base["PRD_MBR_SID"] = value;
                }
            }
        }

        public Nullable<Int32> SEG_MBR_SID
        {
            get
            {
                if (base.IsNull("SEG_MBR_SID")) { return null; }
                return (Nullable<Int32>)base["SEG_MBR_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["SEG_MBR_SID"] = DBNull.Value;
                }
                else
                {
                    base["SEG_MBR_SID"] = value;
                }
            }
        }

        public Nullable<Int32> LAYER1_SID
        {
            get
            {
                if (base.IsNull("LAYER1_SID")) { return null; }
                return (Nullable<Int32>)base["LAYER1_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["LAYER1_SID"] = DBNull.Value;
                }
                else
                {
                    base["LAYER1_SID"] = value;
                }
            }
        }

        public Nullable<Int32> LAYER2_SID
        {
            get
            {
                if (base.IsNull("LAYER2_SID")) { return null; }
                return (Nullable<Int32>)base["LAYER2_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["LAYER2_SID"] = DBNull.Value;
                }
                else
                {
                    base["LAYER2_SID"] = value;
                }
            }
        }

        public Nullable<Int32> LAYER3_SID
        {
            get
            {
                if (base.IsNull("LAYER3_SID")) { return null; }
                return (Nullable<Int32>)base["LAYER3_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["LAYER3_SID"] = DBNull.Value;
                }
                else
                {
                    base["LAYER3_SID"] = value;
                }
            }
        }

        public Nullable<Int32> LAYER4_SID
        {
            get
            {
                if (base.IsNull("LAYER4_SID")) { return null; }
                return (Nullable<Int32>)base["LAYER4_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["LAYER4_SID"] = DBNull.Value;
                }
                else
                {
                    base["LAYER4_SID"] = value;
                }
            }
        }

        public Nullable<Int32> LAYER5_SID
        {
            get
            {
                if (base.IsNull("LAYER5_SID")) { return null; }
                return (Nullable<Int32>)base["LAYER5_SID"];
            }
            set
            {
                if (value == null)
                {
                    base["LAYER5_SID"] = DBNull.Value;
                }
                else
                {
                    base["LAYER5_SID"] = value;
                }
            }
        }

        public String ATRB_VAL
        {
            get
            {
                if (base.IsNull("ATRB_VAL")) { return default(String); }
                return (String)base["ATRB_VAL"];
            }
            set
            {
                base["ATRB_VAL"] = value;
            }
        }

    }

} // namespace

