export class inactiveSearchClmn {
    static "INACTV_CUST_COLS" = [
        {
            "field": "CNTRCT_OBJ_SID",
            "title": "Contract Id",
            "width": 80,
            "template": "#=gridUtils.uiControlWrapper(data, 'CNTRCT_OBJ_SID')#",
            "excelTemplate": "#=CNTRCT_OBJ_SID#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": true,
            "lockable": false
        },
        {
            "field": "PS_OBJ_SID",
            "title": "PS ID",
            "width": 90,
            "template": "#=gridUtils.uiControlWrapper(data, 'PS_OBJ_SID')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PT_OBJ_SID",
            "title": "Prc Table ID",
            "width": 90,
            "template": "#=gridUtils.uiControlWrapper(data, 'PT_OBJ_SID')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DC_PARENT_ID",
            "title": "Prc Table Row ID",
            "width": 90,
            "template": "#=gridUtils.uiControlWrapper(data, 'DC_PARENT_ID')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DC_ID",
            "title": "Deal Id",
            "width": 90,
            "template": "#=gridUtils.uiControlDealWrapper(data, 'DC_ID')#",
            "excelTemplate": "#=DC_ID#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": true,
            "lockable": false
        },
        {
            "field": "REBATE_TYPE",
            "title": "Rebate Type",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_TYPE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/REBATE_TYPE/KIT",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "OBJ_SET_TYPE_CD",
            "title": "Deal Type",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'OBJ_SET_TYPE_CD')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "details",
            "title": "Deal Details",
            "width": 260,
            "template": "<div><deal-detail ng-model='dataItem'></deal-detail></div>",
            "bypassExport": true,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": true,
            "lockable": false
        },
        //{
        //    "field": "tools",
        //    "title": "Deal Tools",
        //    "width": 230,
        //    "template": "<div><deal-tools ng-model='dataItem' is-editable='true'></deal-tools></div>",
        //    "bypassExport": true,
        //    "hidden": false,
        //    "isDimKey": false,
        //    "isRequired": false,
        //    "sortable": false,
        //    "filterable": false,
        //    "headerTemplate": "<input type='checkbox' ng-click='clkAllItems()' class='with-font' id='chkDealTools' /><label for='chkDealTools' style='margin: 5px 0 0 5px;'>Deal Tools</label>",
        //    "mjrMnrChg": null,
        //    "lookupUrl": "",
        //    "lookupText": "",
        //    "lookupValue": "",
        //    "locked": true,
        //    "lockable": false
        //},
        {
            "field": "PASSED_VALIDATION",
            "title": "Passed Validation",//"<i class='intelicon-protection-solid' style='color: #00AEEF; font-size: 20px;'></i>",
            "width": 50,
            "template": "#=gridUtils.uiValidationErrorDetail(data)#",
            "excelTemplate": "#=PASSED_VALIDATION#",
            "excelHeaderLabel": "Validation Status",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CUST_MBR_SID",
            "title": "Customer",
            "width": 100,
            "template": "#=gridUtils.uiCustomerControlWrapper(data, 'CUST_MBR_SID')#",
            "excelTemplate": "#=Customer.CUST_NM#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title='Customer (or Division if present)'>Customer</span>",
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TRKR_NBR",
            "title": "Tracker Number",
            "width": 130,
            "template": "#=gridUtils.uiDimTrkrControlWrapper(data)#",
            "excelTemplate": "#=gridUtils.exportDimTrkrControlWrapper(data)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Tracker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "START_DT",
            "title": "Deal Start Date",
            "width": 100,
            "template": "#=gridUtils.uiStartDateWrapper(data, 'START_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(START_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_DECREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "END_DT",
            "title": "Deal End Date",
            "width": 100,
            "template": "#=gridUtils.uiControlEndDateWrapper(data, 'END_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(END_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "EXPIRE_FLG",
            "title": "Deal Expired?",
            "width": 90,
            "template": "#=gridUtils.uiBoolControlWrapper(data, 'EXPIRE_FLG')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "CheckBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "WF_STG_CD",
            "title": "Stage",
            "width": 100,
            "template": "#=gridUtils.uiParentControlWrapper(data, 'PS_WF_STG_CD')#",
            "excelTemplate": "#=gridUtils.stgFullTitleChar(data)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "WorkFlow",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PTR_USER_PRD",
            "title": "Contract Product",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'PTR_USER_PRD')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRODUCT_CATEGORIES",
            "title": "Product Vertical",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'PRODUCT_CATEGORIES')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PROD_INCLDS",
            "title": "Media",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'PROD_INCLDS')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEAL_DESC",
            "title": "Deal Description",
            "width": 200,
            "template": "#=gridUtils.uiControlWrapper(data, 'DEAL_DESC')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SETTLEMENT_PARTNER",
            "title": "Settlement Partner",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'SETTLEMENT_PARTNER')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/CustomerVendor/GetCustomerVendors",
            "lookupText": "BUSNS_ORG_NM",
            "lookupValue": "BUSNS_ORG_NM",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_COUNTRY_REGION",
            "title": "Consumption Country/Region",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_COUNTRY_REGION')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title = 'This field applies to only Consumption based' > Consumption Country/Region </span>",
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetConsumptionCountryHierarchy/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SEND_TO_VISTEX",
            "title": "Send to Vistex",
            "width": 80,
            "template": "#=gridUtils.uiControlWrapper(data, 'SEND_TO_VISTEX')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/SEND_TO_VISTEX",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "BACK_DATE_RSN",
            "title": "Backdate Reason",
            "width": 220,
            "template": "#=gridUtils.uiControlWrapper(data, 'BACK_DATE_RSN')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/BACK_DATE_RSN",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PAYOUT_BASED_ON",
            "title": "Payout Based On",
            "width": 110,
            "template": "#=gridUtils.uiControlWrapper(data, 'PAYOUT_BASED_ON')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/PAYOUT_BASED_ON",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PROGRAM_PAYMENT",
            "title": "Program Payment",
            "width": 110,
            "template": "#=gridUtils.uiControlWrapper(data, 'PROGRAM_PAYMENT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/PROGRAM_PAYMENT",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "MRKT_SEG",
            "title": "Market Segment",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'MRKT_SEG')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdownHierarchy/MRKT_SEG",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONTRACT_TYPE",
            "title": "Contract Type",
            "width": 220,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONTRACT_TYPE')#",
            "excelTemplate": "#=CONTRACT_TYPE#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/CONTRACT_TYPE",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "GEO_COMBINED",
            "title": "Geo",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'GEO_COMBINED')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "MULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetGeosDropdowns",
            "lookupText": "dropdownName",
            "lookupValue": "dropdownName",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TRGT_RGN",
            "title": "Target Sales Geo",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'TRGT_RGN')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetGeoDropdownHierarchy/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "END_CUSTOMER_RETAIL",
            "title": "End Customer/Retail",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'END_CUSTOMER_RETAIL')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title = 'This field applies to only Consumption based' > End Customer/Retail </span>",
            "mjrMnrChg": "MAJOR_QUOTEONLY",
            "lookupUrl": "/api/PrimeCustomers/GetPrimeCustomers",
            "lookupText": "Text",
            "lookupValue": "Value",
            "locked": false,
            "lockable": false
        },
        {
            "field": "END_CUST_OBJ",
            "title": "END_CUST_OBJ",
            "width": 0,
            "template": "#=gridUtils.uiControlWrapper(data, 'END_CUST_OBJ')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRIMED_CUST_NM",
            "title": "Unified Customer Name",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'PRIMED_CUST_NM')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRIMED_CUST_CNTRY",
            "title": "Unified Customer Country/Region",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'PRIMED_CUST_CNTRY')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRIMED_CUST_ID",
            "title": "Unified Customer ID",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'PRIMED_CUST_ID')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "IS_PRIMED_CUST",
            "title": "Is Unified Cust",
            "width": 130,
            "template": "#=gridUtils.uiControlWrapper(data, 'IS_PRIMED_CUST')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "CheckBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "IS_RPL",
            "title": "Is RPL Cust",
            "width": 130,
            "template": "#=gridUtils.uiControlWrapper(data, 'IS_RPL')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "CheckBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TERMS",
            "title": "Additional Ts And Cs",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'TERMS')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_QUOTEONLY",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "QUOTE_LN_ID",
            "title": "Quote Line Number",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'QUOTE_LN_ID')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "REBATE_OA_MAX_AMT",
            "title": "Overarching Max Dollar",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_OA_MAX_AMT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "REBATE_DEAL_ID",
            "title": "Overarching Deal IDs",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_DEAL_ID')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CREDIT_VOLUME",
            "title": "Credit Volume",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'CREDIT_VOLUME', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEBIT_VOLUME",
            "title": "Debit Volume",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'DEBIT_VOLUME', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CREDIT_AMT",
            "title": "Credit Dollar",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'CREDIT_AMT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEBIT_AMT",
            "title": "Debit Dollar",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'DEBIT_AMT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TOTAL_CR_DB_PERC",
            "title": "Total Deal Volume",
            "width": 140,
            "template": "#=gridUtils.uiCrDbPercWrapper(data)#",
            "excelTemplate": "#=gridUtils.uiCrDbPercExcelWrapper(data)#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "BLLG_DT",
            "title": "Last Credit/Debit Payment Date",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'BLLG_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(BLLG_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "MISSING_CAP_COST_INFO",
            "title": "Missing Cost/CAP",//"<div title='Deals missing Cost and/or CAP cannot be approved by Division Approvers until the missing data has been added. For urgent issues, contact TAC.'>Missing Cost/CAP</div>",
            "width": 150,
            "template": "#=gridUtils.getMissingCostCapIcon(data)#",
            "excelTemplate": "#=gridUtils.getMissingCostCapTitle(data)#",
            "excelHeaderLabel": "Missing Cost/CAP",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "AR_SETTLEMENT_LVL",
            "title": "Settlement Level",
            "width": 240,
            "template": "#=gridUtils.uiControlWrapper(data, 'AR_SETTLEMENT_LVL')#",
            "excelTemplate": "#=AR_SETTLEMENT_LVL#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/AR_SETTLEMENT_LVL",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "LAST_REDEAL_DT",
            "title": "Effective Tracker Start Date",//"<div title='Date the current deal values took effect. This date can be changed on a re-deal.'>Effective Tracker Start Date</div>",
            "width": 120,
            "template": "#=gridUtils.uiStartDateWrapper(data, 'LAST_REDEAL_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(LAST_REDEAL_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "LAST_TRKR_START_DT_CHK",
            "title": "Last Tracker Start Date",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'LAST_TRKR_START_DT_CHK', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(LAST_TRKR_START_DT_CHK)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        //{
        //    "field": "tender_actions",
        //    "title": "Actions",
        //    "width": 110,
        //    "template": "<div id='cb_actn_#=data.DC_ID#'>#=gridUtils.getBidActions(data)#</div>",
        //    "bypassExport": true,
        //    "hidden": false,
        //    "editor": "BID_ACTNS",
        //    "isDimKey": false,
        //    "isRequired": false,
        //    "sortable": false,
        //    "filterable": false,
        //    "mjrMnrChg": null,
        //    "lookupUrl": "",
        //    "lookupText": "",
        //    "lookupValue": "",
        //    "locked": true,
        //    "lockable": false
        //},
        {
            "field": "COMPETITIVE_PRICE",
            "title": "Meet Comp Price",
            "width": 100,
            "template": "<div class=\"uiControlDiv isReadOnlyCell\">#=gridUtils.uiDimControlWrapper(data, 'COMPETITIVE_PRICE', '20___0', 'currency')#</div>",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": true,
            "isRequired": false,
            "sortable": true,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "COMP_SKU",
            "title": "Meet Comp SKU",
            "width": 100,
            "template": "<div class=\"uiControlDiv isReadOnlyCell\"><div class=\"vert-center\">#=gridUtils.getFormatedDim(data, 'TempCOMP_SKU', '20___0', 'string')#</div></div>",
            "bypassExport": false,
            "hidden": false,
            "uiType": "CMNT_HIST",
            "isDimKey": true,
            "isRequired": false,
            "sortable": true,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "ON_ADD_DT",
            "title": "On Ad Date",
            "width": 110,
            "template": "#=gridUtils.uiControlWrapper(data, 'ON_ADD_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(ON_ADD_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEAL_SOLD_TO_ID",
            "title": "Sold To Id",
            "width": 150,
            "template": "#=gridUtils.uiMultiselectArrayControlWrapper(data, 'DEAL_SOLD_TO_ID')#",
            "excelTemplate": "#=DEAL_SOLD_TO_ID#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetSoldToIds",
            "lookupText": "dropdownName",
            "lookupValue": "dropdownName",
            "locked": false,
            "lockable": false
        },
        {
            "field": "EXPIRE_YCS2",
            "title": "Expire YCS2",
            "width": 115,
            "template": "#=gridUtils.uiControlWrapper(data, 'EXPIRE_YCS2')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/EXPIRE_YCS2",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "ECAP_PRICE",
            "title": "ECAP Price",
            "width": 130,
            "template": "#=gridUtils.uiDimControlWrapper(data, 'ECAP_PRICE', '20___0', 'currency')#",
            "excelTemplate": "#=gridUtils.exportDimControlWrapper(data, 'ECAP_PRICE', '20___0', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "NumericTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "BACKEND_REBATE",
            "title": "Rebate",
            "width": 130,
            "template": "#=gridUtils.uiControlBackEndRebateWrapper(data, 'ECAP', 'ECAP_PRICE', '20___0', 'currency')#",
            "excelTemplate": "#=gridUtils.exportBackEndRebateWrapper(data, 'ECAP', 'ECAP_PRICE', '20___0', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CAP_INFO",
            "title": "CAP Info",
            "width": 150,
            "template": "#=gridUtils.uiDimInfoControlWrapper(data, 'CAP')#",
            "excelTemplate": "#=gridUtils.uiDimInfoExcelControlWrapper(data, 'CAP')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "NumericTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CAP",
            "title": "CAP",
            "width": 130,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'CAP', 'currency')#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'CAP', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CAP_STRT_DT",
            "title": "CAP Start Date",
            "width": 100,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'CAP_STRT_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'CAP_STRT_DT', 'date')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CAP_END_DT",
            "title": "CAP End Date",
            "width": 100,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'CAP_END_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'CAP_END_DT', 'date')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_INFO",
            "title": "YCS2 Info",
            "width": 150,
            "template": "#=gridUtils.uiDimInfoControlWrapper(data, 'YCS2')#",
            "excelTemplate": "#=gridUtils.uiDimInfoExcelControlWrapper(data, 'YCS2')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_PRC_IRBT",
            "title": "YCS2 Price",
            "width": 130,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'YCS2_PRC_IRBT', 'currency')#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'YCS2_PRC_IRBT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_START_DT",
            "title": "YCS2 Start Date",
            "width": 100,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'YCS2_START_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'YCS2_START_DT', 'date')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "LINK_LABEL",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_END_DT",
            "title": "YCS2 End Date",
            "width": 100,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'YCS2_END_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'YCS2_END_DT', 'date')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "LINK_LABEL",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_OVERLAP_OVERRIDE",
            "title": "YCS2 Overlp Override",
            "width": 110,
            "template": "#=gridUtils.uiControlWrapper(data, 'YCS2_OVERLAP_OVERRIDE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/YCS2_OVERLAP_OVERRIDE",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "VOLUME",
            "title": "Ceiling Volume",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'VOLUME', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "IntegerTextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "QLTR_BID_GEO",
            "title": "Bid Geo",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'QLTR_BID_GEO')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "MULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetGeosDropdowns",
            "lookupText": "dropdownName",
            "lookupValue": "dropdownName",
            "locked": false,
            "lockable": false
        },
        {
            "field": "REBATE_OA_MAX_VOL",
            "title": "Overarching Max Volume",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_OA_MAX_VOL', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "IntegerTextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "MEETCOMP_TEST_RESULT",
            "title": "Deal Meet Comp Test Result",
            "width": 150,
            "template": "#=gridUtils.getResultSingleIcon(data, 'MEETCOMP_TEST_RESULT')#",
            "excelTemplate": "#=MEETCOMP_TEST_RESULT#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        //{
        //    "field": "EXCLUDE_AUTOMATION",
        //    "title": "Exclude from Price Rules",//"<div title='Exclude from Price Approval Rules'>Exclude from Price Rules</div>",
        //    "width": 120,
        //    "template": "#=gridUtils.uiControlWrapper(data, 'EXCLUDE_AUTOMATION')#",
        //    "excelTemplate": "#=EXCLUDE_AUTOMATION#",
        //    "bypassExport": true,
        //    "hidden": false,
        //    "uiType": "TextBox",
        //    "isDimKey": false,
        //    "isRequired": false,
        //    "sortable": true,
        //    "filterable": true,
        //    "mjrMnrChg": "MINOR",
        //    "lookupUrl": "/api/Dropdown/GetDropdowns/EXCLUDE_AUTOMATION/",
        //    "lookupText": "DROP_DOWN",
        //    "lookupValue": "DROP_DOWN",
        //    "locked": false,
        //    "lockable": false
        //},
        {
            "field": "COST_TEST_RESULT",
            "title": "Deal Cost Test Result",
            "width": 150,
            "template": "#=gridUtils.getResultSingleIcon(data, 'COST_TEST_RESULT')#",
            "excelTemplate": "#=COST_TEST_RESULT#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "GEO_APPROVED_BY",
            "title": "Geo Approved By",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'GEO_APPROVED_BY')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "na",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DIV_APPROVED_BY",
            "title": "Div Approved By",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'DIV_APPROVED_BY')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "na",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "AUTO_APPROVE_RULE_INFO",
            "title": "Auto-approved By",
            "width": 320,
            "template": "#=gridUtils.uiReadonlyControlWrapper(data, 'AUTO_APPROVE_RULE_INFO')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRD_EXCLDS",
            "title": "Excluded Products",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'PRD_EXCLDS')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TITLE",
            "title": "My Deals Product",
            "width": 150,
            "template": "#=gridUtils.uiProductControlWrapper(data, 'TITLE')#",
            "excelTemplate": "#=TITLE#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEAL_COMB_TYPE",
            "title": "Group Type",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'DEAL_COMB_TYPE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/DEAL_COMB_TYPE/PROGRAM",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TIER_NBR",
            "title": "Rate Breakout",
            "width": 300,
            "template": "#=gridUtils.uiControlScheduleWrapperRevTier(data)#",
            "excelTemplate": "#=gridUtils.exportControlScheduleWrapperRevTier(data)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "editor": "scheduleEditorRevTier",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "REBATE_BILLING_START",
            "title": "Billings START Date (for Consumption)",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_BILLING_START', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(REBATE_BILLING_START)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_DECREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "REBATE_BILLING_END",
            "title": "Billings END Date (for Consumption)",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'REBATE_BILLING_END', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(REBATE_BILLING_END)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_TYPE",
            "title": "Consumption Type",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_TYPE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdowns/CONSUMPTION_TYPE",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_REASON",
            "title": "Consumption Reason",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_REASON')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdowns/CONSUMPTION_REASON",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_REASON_CMNT",
            "title": "Consumption Reason Comment",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_REASON_CMNT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_CUST_PLATFORM",
            "title": "Customer Platform",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_CUST_PLATFORM')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/CONSUMPTION_CUST_PLATFORM/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_CUST_SEGMENT",
            "title": "Customer Segment",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_CUST_SEGMENT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/CONSUMPTION_CUST_SEGMENT/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_CUST_RPT_GEO",
            "title": "Customer Reported Sales Geo",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_CUST_RPT_GEO')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title='Consumption Customer Reported Sales Geo'>Customer Reported Sales Geo</span>",
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/CONSUMPTION_CUST_RPT_GEO/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_LOOKBACK_PERIOD",
            "title": "Billing Rolling Lookback Period (Months)",
            "width": 170,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_LOOKBACK_PERIOD', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "IntegerTextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "Billing Rolling Lookback Period (Months) <span title='Invoice eligibility time period for rebate payment. Could be a rolling number of months or equal to billings dates. Enter 0 (zero) for deals using billing start and end date.'><i class='intelicon-help' style='font-size: 15px !important'></i></span>",
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SYS_PRICE_POINT",
            "title": "System Price Point",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'SYS_PRICE_POINT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "SPP",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdownHierarchy/MRKT_SEG",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CONSUMPTION_SYS_CONFIG",
            "title": "System Configuration",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'CONSUMPTION_SYS_CONFIG')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "EMBEDDEDMULTISELECT",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/CONSUMPTION_SYS_CONFIG/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {

            "field": "SERVER_DEAL_TYPE",
            "title": "Server Deal Type",
            "width": 110,
            "template": "#=gridUtils.uiControlWrapper(data, 'SERVER_DEAL_TYPE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/SERVER_DEAL_TYPE/ECAP",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "QLTR_PROJECT",
            "title": "Project Name",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'QLTR_PROJECT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title = 'This field applies to only Consumption based' > Project Name </span>",
            "mjrMnrChg": "MAJOR_FASTTRACK",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "NUM_OF_TIERS",
            "title": "Number of Tiers",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'NUM_OF_TIERS')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "NUM_OF_DENSITY",
            "title": "Number of Density Bands",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'NUM_OF_DENSITY')#",
            "bypassExport": false,
            "hidden": true,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "FRCST_VOL",
            "title": "Forecast Volume",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'FRCST_VOL', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "MAX_RPU",
            "title": "Max RPU",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'MAX_RPU', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "USER_MAX_RPU",
            "title": "User Defined Max RPU",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'USER_MAX_RPU', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "AVG_RPU",
            "title": "Average RPU",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'AVG_RPU', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "USER_AVG_RPU",
            "title": "User Defined Average RPU",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'USER_AVG_RPU', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "Label",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "RPU_OVERRIDE_CMNT",
            "title": "User Defined RPU Override Comment",
            "width": 180,
            "template": "#=gridUtils.uiControlWrapper(data, 'RPU_OVERRIDE_CMNT')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PERIOD_PROFILE",
            "title": "Period Profile",
            "width": 160,
            "template": "#=gridUtils.uiControlWrapper(data, 'PERIOD_PROFILE')#",
            "excelTemplate": "#=PERIOD_PROFILE#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdownsWithCustomerId/PERIOD_PROFILE/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "RESET_VOLS_ON_PERIOD",
            "title": "Reset Per Period",
            "width": 140,
            "template": "#=gridUtils.uiControlWrapper(data, 'RESET_VOLS_ON_PERIOD')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DropDownList",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/RESET_VOLS_ON_PERIOD",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "FLEX_ROW_TYPE",
            "title": "Row Type",
            "width": 80,
            "template": "#=gridUtils.uiControlWrapper(data, 'FLEX_ROW_TYPE')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/Dropdown/GetDropdowns/FLEX_ROW_TYPE",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DEAL_GRP_NM",
            "title": "Kit Name",
            "width": 150,
            "template": "#=gridUtils.uiControlWrapper(data, 'DEAL_GRP_NM')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        //{
        //    "field": "PRD_BCKT",
        //    "title": "My Deals Products",
        //    "width": 140,
        //    "template": "#=gridUtils.uiProductDimControlWrapper(data, 'kit')#",
        //    "excelTemplate": "#=PTR_USER_PRD#",
        //    "bypassExport": false,
        //    "hidden": false,
        //    "uiType": "TextBox",
        //    "isDimKey": true,
        //    "isRequired": false,
        //    "sortable": false,
        //    "filterable": false,
        //    "mjrMnrChg": "MINOR",
        //    "lookupUrl": "",
        //    "lookupText": "",
        //    "lookupValue": "",
        //    "locked": false,
        //    "lockable": false
        //},
        {
            "field": "PRD_BCKT_SUBKIT",
            "title": "Sub KIT Products",
            "width": 140,
            "template": "#=gridUtils.uiProductDimControlWrapper(data, 'subkit')#",
            "excelTemplate": "#=PTR_USER_PRD#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": true,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CS_SHIP_AHEAD_STRT_DT",
            "title": "CS Ship Ahead Start Date",
            "width": 115,
            "template": "#=gridUtils.uiControlWrapper(data, 'CS_SHIP_AHEAD_STRT_DT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CS_SHIP_AHEAD_END_DT",
            "title": "CS Ship Ahead End Date",
            "width": 115,
            "template": "#=gridUtils.uiControlWrapper(data, 'CS_SHIP_AHEAD_END_DT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "ComboBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "KIT_ECAP",
            "title": "Net KIT Price (Kit ECAP)",
            "width": 130,
            "template": "#=gridUtils.uiDimControlWrapper(data, 'ECAP_PRICE', '20_____1', 'currency')#",
            "excelTemplate": "#=gridUtils.exportDimControlWrapper(data, 'ECAP_PRICE', '20_____1', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "NumericTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SUBKIT_ECAP",
            "title": "Net Subkit Price (Subkit ECAP)",
            "width": 130,
            "template": "#=gridUtils.uiDimControlWrapper(data, 'ECAP_PRICE', '20_____2', 'currency')#",
            "excelTemplate": "#=gridUtils.exportDimControlWrapper(data, 'ECAP_PRICE', '20_____2', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "NumericTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "PRIMARY_OR_SECONDARY",
            "title": "Primary or Secondary",
            "width": 100,
            "template": "#=gridUtils.uiPrimarySecondaryDimControlWrapper(data)#",
            "excelTemplate": "#=gridUtils.exportPrimarySecondaryDimControlWrapper(data)#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "KIT_REBATE_BUNDLE_DISCOUNT",
            "title": "Kit Discount (ECAP value only)",
            "width": 130,
            "template": "#=gridUtils.uiKitCalculatedValuesControlWrapper(data, 'kit', 'rebateBundle')#",
            "excelTemplate": "#=gridUtils.exportKitCalculatedValuesControlWrapper(data, 'kit', 'rebateBundle')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SUBKIT_REBATE_BUNDLE_DISCOUNT",
            "title": "Sub Kit Discount (ECAP value only)",
            "width": 130,
            "template": "#=gridUtils.uiKitCalculatedValuesControlWrapper(data, 'subkit', 'rebateBundle')#",
            "excelTemplate": "#=gridUtils.exportKitCalculatedValuesControlWrapper(data, 'subkit', 'rebateBundle')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "DSCNT_PER_LN",
            "title": "Discount per line",
            "width": 130,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'DSCNT_PER_LN', 'currency')#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'DSCNT_PER_LN', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "NumericTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "QTY",
            "title": "Quantity",
            "width": 100,
            "template": "#=gridUtils.uiPositiveDimControlWrapper(data, 'QTY', 'number')#",
            "excelTemplate": "#=gridUtils.exportPositiveDimControlWrapper(data, 'QTY', 'number')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "IntegerTextBox",
            "editor": "multiDimEditor",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TOTAL_DSCNT_PR_LN",
            "title": "Total Discount per line",
            "width": 130,
            "template": "#=gridUtils.uiTotalDiscountPerLineControlWrapper(data, 'currency')#",
            "excelTemplate": "#=gridUtils.exportTotalDiscountPerLineControlWrapper(data, 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "KIT_SUM_OF_TOTAL_DISCOUNT_PER_LINE",
            "title": "KIT Sum of Total Discount Per Line",
            "width": 130,
            "template": "#=gridUtils.uiKitCalculatedValuesControlWrapper(data, 'kit', 'sumTD')#",
            "excelTemplate": "#=gridUtils.exportKitCalculatedValuesControlWrapper(data, 'kit', 'sumTD')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "SUBKIT_SUM_OF_TOTAL_DISCOUNT_PER_LINE",
            "title": "Sub KIT Sum of Total Discount Per Line",
            "width": 130,
            "template": "#=gridUtils.uiKitCalculatedValuesControlWrapper(data, 'subkit', 'sumTD')#",
            "excelTemplate": "#=gridUtils.exportKitCalculatedValuesControlWrapper(data, 'subkit', 'sumTD')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "HAS_SUBKIT",
            "title": "Has Subkit",
            "width": 130,
            "template": "#=gridUtils.uiControlWrapper(data, 'HAS_SUBKIT')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "CheckBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "CAP_KIT",
            "title": "CAP Kit",
            "width": 130,
            "template": "#=gridUtils.uiDimControlWrapper(data, 'CAP', '20_____1', 'currency')#",
            "excelTemplate": "#=gridUtils.exportDimControlWrapper(data, 'CAP', '20_____1', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "YCS2_KIT",
            "title": "YCS2 Price Kit",
            "width": 130,
            "template": "#=gridUtils.uiDimControlWrapper(data, 'YCS2_PRC_IRBT', '20_____1', 'currency')#",
            "excelTemplate": "#=gridUtils.exportDimControlWrapper(data, 'YCS2_PRC_IRBT', '20_____1', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "isDimKey": false,
            "isRequired": false,
            "sortable": false,
            "filterable": false,
            "mjrMnrChg": null,
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "OEM_PLTFRM_LNCH_DT",
            "title": "OEM Platform Launch Date",
            "width": 100,
            "template": "#=gridUtils.uiControlEndDateWrapper(data, 'OEM_PLTFRM_LNCH_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(OEM_PLTFRM_LNCH_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "OEM_PLTFRM_EOL_DT",
            "title": "OEM Platform EOL Date",
            "width": 100,
            "template": "#=gridUtils.uiControlEndDateWrapper(data, 'OEM_PLTFRM_EOL_DT', \"date:'MM/dd/yyyy'\")#",
            "excelTemplate": "#=gridUtils.formatDate(OEM_PLTFRM_EOL_DT)#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DatePicker",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "ORIG_ECAP_TRKR_NBR",
            "title": "Original Tracker #",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'ORIG_ECAP_TRKR_NBR')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "DROPDOWN",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "/api/EcapTracker/GetEcapTrackerList/",
            "lookupText": "DROP_DOWN",
            "lookupValue": "DROP_DOWN",
            "locked": false,
            "lockable": false
        },
        {
            "field": "TOTAL_DOLLAR_AMOUNT",
            "title": "Total Dollar Amount",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'TOTAL_DOLLAR_AMOUNT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "ADJ_ECAP_UNIT",
            "title": "Adjustment Ecap Unit",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'ADJ_ECAP_UNIT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "mjrMnrChg": "MINOR",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        },
        {
            "field": "MAX_PAYOUT",
            "title": "Max Payout",
            "width": 100,
            "template": "#=gridUtils.uiControlWrapper(data, 'MAX_PAYOUT', 'currency')#",
            "bypassExport": false,
            "hidden": false,
            "uiType": "TextBox",
            "isDimKey": false,
            "isRequired": false,
            "sortable": true,
            "filterable": true,
            "headerTemplate": "<span title = 'Max Payout cannot be $0.00 value and must reflect the actual payout for all combined Tiers' > Max Payout <i class=\"intelicon-help\" style=\"font-size: 15px !important\"></i></span>",
            "mjrMnrChg": "MAJOR_INCREASE",
            "lookupUrl": "",
            "lookupText": "",
            "lookupValue": "",
            "locked": false,
            "lockable": false
        }
    ]
    "INACTIVE_CUST_TEMPLATE": {
        "CNTRCT_OBJ_SID": {
            "Groups": ["Deal Info"]
        },
        "PS_OBJ_SID": {
            "Groups": ["Deal Info"]
        },
        "PT_OBJ_SID": {
            "Groups": ["Deal Info"]
        },
        "DC_PARENT_ID": {
            "Groups": ["Deal Info"]
        },
        "DC_ID": {
            "Groups": ["Deal Info"]
        },
        "REBATE_TYPE": {
            "Groups": ["Deal Info"]
        },
        "OBJ_SET_TYPE_CD": {
            "Groups": ["All"]
        },
        /*"tools": {
            "Groups": ["Deal Info", "Consumption", "Cost Test", "Meet Comp", "Backdate", "RPU", "Payment"]
        },*/
        "details": {
            "Groups": ["Consumption", "Cost Test", "Meet Comp", "Backdate", "RPU", "Payment"]
        },
        "PASSED_VALIDATION": {
            "Groups": ["Deal Info"]
        },
        "CUST_MBR_SID": {
            "Groups": ["Deal Info"]
        },
        "TRKR_NBR": {
            "Groups": ["Deal Info"]
        },
        "START_DT": {
            "Groups": ["Deal Info"]
        },
        "END_DT": {
            "Groups": ["Deal Info"]
        },
        "EXPIRE_FLG": {
            "Groups": ["All"]
        },
        "WF_STG_CD": {
            "Groups": ["Deal Info"]
        },
        "PTR_USER_PRD": {
            "Groups": ["Deal Info"]
        },
        "PRODUCT_CATEGORIES": {
            "Groups": ["Deal Info"]
        },
        "PROD_INCLDS": {
            "Groups": ["Deal Info"]
        },
        "DEAL_DESC": {
            "Groups": ["Deal Info"]
        },
        "SETTLEMENT_PARTNER": {
            "Groups": ["Deal Info", "Payment"]
        },
        "CONSUMPTION_COUNTRY_REGION": {
            "Groups": ["Consumption"]
        },
        "SEND_TO_VISTEX": {
            "Groups": ["Deal Info"]
        },
        "BACK_DATE_RSN": {
            "Groups": ["Backdate"]
        },
        "PAYOUT_BASED_ON": {
            "Groups": ["Deal Info", "Consumption"]
        },
        "PROGRAM_PAYMENT": {
            "Groups": ["Deal Info"]
        },
        "MRKT_SEG": {
            "Groups": ["Deal Info"]
        },
        "CONTRACT_TYPE": {
            "Groups": ["Deal Info"]
        },
        "GEO_COMBINED": {
            "Groups": ["Deal Info"]
        },
        "TRGT_RGN": {
            "Groups": ["Deal Info"]
        },
        "END_CUSTOMER_RETAIL": {
            "Groups": ["Deal Info"] //, "Consumption"
        },
        /*"END_CUST_OBJ": {
            "Groups": []
        },*/
        /*"PRIMED_CUST_NM": {
            "Groups": []
        },*/
        "PRIMED_CUST_CNTRY": {
            "Groups": ["Deal Info"]
        },
        /*"PRIMED_CUST_ID": {
            "Groups": []
        },*/
        /*"IS_PRIMED_CUST": {
            "Groups": []
        },*/
        /*"IS_RPL": {
            "Groups": []
        },*/
        "TERMS": {
            "Groups": ["Deal Info"]
        },
        "QUOTE_LN_ID": {
            "Groups": ["Deal Info"]
        },
        "REBATE_OA_MAX_AMT": {
            "Groups": ["All"]
        },
        /*"REBATE_DEAL_ID": {
            "Groups": []
        },*/
        "CREDIT_VOLUME": {
            "Groups": ["Payment"]
        },
        "DEBIT_VOLUME": {
            "Groups": ["Payment"]
        },
        "CREDIT_AMT": {
            "Groups": ["Payment"]
        },
        "DEBIT_AMT": {
            "Groups": ["Payment"]
        },
        "TOTAL_CR_DB_PERC": {
            "Groups": ["Payment"]
        },
        "BLLG_DT": {
            "Groups": ["Payment"]
        },
        "MISSING_CAP_COST_INFO": {
            "Groups": ["Deal Info"]
        },
        "AR_SETTLEMENT_LVL": {
            "Groups": ["Deal Info", "Payment"]
        },
        "LAST_REDEAL_DT": {
            "Groups": ["Deal Info"]
        },
        /*"LAST_TRKR_START_DT_CHK": {
            "Groups": []
        },*/
        /*"tender_actions": {
            "Groups": ["Deal Info", "Consumption", "Cost Test", "Meet Comp", "Backdate", "CAP Info", "SubKit", "Payment"]
        },*/
        "COMPETITIVE_PRICE": {
            "Groups": ["Deal Info"]
        },
        "COMP_SKU": {
            "Groups": ["Deal Info"]
        },
        "ON_ADD_DT": {
            "Groups": ["Deal Info"]
        },
        "DEAL_SOLD_TO_ID": {
            "Groups": ["Deal Info"]
        },
        "EXPIRE_YCS2": {
            "Groups": ["Deal Info"]
        },
        "ECAP_PRICE": {
            "Groups": ["Deal Info", "CAP Info"]
        },
        "BACKEND_REBATE": {
            "Groups": ["Deal Info"]
        },
        "CAP_INFO": {
            "Groups": ["Deal Info", "CAP Info"]
        },
        "CAP": {
            "Groups": ["All", "CAP Info"]
        },
        "CAP_STRT_DT": {
            "Groups": ["All", "CAP Info"]
        },
        "CAP_END_DT": {
            "Groups": ["All", "CAP Info"]
        },
        "YCS2_INFO": {
            "Groups": ["Deal Info"]
        },
        "YCS2_PRC_IRBT": {
            "Groups": ["All"]
        },
        "YCS2_START_DT": {
            "Groups": ["All"]
        },
        "YCS2_END_DT": {
            "Groups": ["All"]
        },
        "YCS2_OVERLAP_OVERRIDE": {
            "Groups": ["All"]
        },
        "VOLUME": {
            "Groups": ["Deal Info", "Payment"]
        },
        "QLTR_BID_GEO": {
            "Groups": ["Deal Info"]
        },
        "REBATE_OA_MAX_VOL": {
            "Groups": ["All"]
        },
        "MEETCOMP_TEST_RESULT": {
            "Groups": ["Deal Info"]
        },
        /*"EXCLUDE_AUTOMATION": {
            "Groups": ["Deal Info"]
        },*/
        "COST_TEST_RESULT": {
            "Groups": ["Deal Info"]
        },
        "GEO_APPROVED_BY": {
            "Groups": ["Deal Info"]
        },
        "DIV_APPROVED_BY": {
            "Groups": ["Deal Info"]
        },
        "AUTO_APPROVE_RULE_INFO": {
            "Groups": ["All"]
        },
        "PRD_EXCLDS": {
            "Groups": ["Deal Info", "RPU"]
        },
        "TITLE": {
            "Groups": ["Deal Info"]
        },
        "DEAL_COMB_TYPE": {
            "Groups": ["Deal Info"]
        },
        "TIER_NBR": {
            "Groups": ["Deal Info"]
        },
        "REBATE_BILLING_START": {
            "Groups": ["Consumption"]
        },
        "REBATE_BILLING_END": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_TYPE": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_REASON": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_REASON_CMNT": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_CUST_PLATFORM": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_CUST_SEGMENT": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_CUST_RPT_GEO": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_LOOKBACK_PERIOD": {
            "Groups": ["Consumption"]
        },
        "SYS_PRICE_POINT": {
            "Groups": ["Consumption"]
        },
        "CONSUMPTION_SYS_CONFIG": {
            "Groups": ["Consumption"]
        },
        "SERVER_DEAL_TYPE": {
            "Groups": ["Deal Info"]
        },
        "QLTR_PROJECT": {
            "Groups": ["Consumption"]
        },
        /*"NUM_OF_TIERS": {
            "Groups": []
        },*/
        /*"NUM_OF_DENSITY": {
            "Groups": []
        },*/
        "FRCST_VOL": {
            "Groups": ["RPU"]
        },
        "MAX_RPU": {
            "Groups": ["RPU"]
        },
        "USER_MAX_RPU": {
            "Groups": ["RPU"]
        },
        "AVG_RPU": {
            "Groups": ["RPU"]
        },
        "USER_AVG_RPU": {
            "Groups": ["RPU"]
        },
        "RPU_OVERRIDE_CMNT": {
            "Groups": ["RPU"]
        },
        "PERIOD_PROFILE": {
            "Groups": ["Deal Info", "Payment"]
        },
        "RESET_VOLS_ON_PERIOD": {
            "Groups": ["Deal Info"]
        },
        "FLEX_ROW_TYPE": {
            "Groups": ["Deal Info"]
        },
        "DEAL_GRP_NM": {
            "Groups": ["Deal Info", "SubKit"]
        },
        /*"PRD_BCKT": {
            "Groups": ["Deal Info", "SubKit"]
        },*/
        "HAS_SUBKIT": {
            "Groups": ["All"]
        },
        "PRD_BCKT_SUBKIT": {
            "Groups": ["SubKit"]
        },
        "CS_SHIP_AHEAD_STRT_DT": {
            "Groups": ["All"]
        },
        "CS_SHIP_AHEAD_END_DT": {
            "Groups": ["All"]
        },
        "KIT_ECAP": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "SUBKIT_ECAP": {
            "Groups": ["SubKit"]
        },
        "PRIMARY_OR_SECONDARY": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "KIT_REBATE_BUNDLE_DISCOUNT": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "SUBKIT_REBATE_BUNDLE_DISCOUNT": {
            "Groups": ["SubKit"]
        },
        "DSCNT_PER_LN": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "QTY": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "TOTAL_DSCNT_PR_LN": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "KIT_SUM_OF_TOTAL_DISCOUNT_PER_LINE": {
            "Groups": ["Deal Info", "SubKit"]
        },
        "SUBKIT_SUM_OF_TOTAL_DISCOUNT_PER_LINE": {
            "Groups": ["SubKit"]
        },
        "CAP_KIT": {
            "Groups": ["Deal Info", "CAP Info"]
        },
        "YCS2_KIT": {
            "Groups": ["All"]
        },
        "OEM_PLTFRM_LNCH_DT": {
            "Groups": ["Deal Info"]
        },
        "OEM_PLTFRM_EOL_DT": {
            "Groups": ["Deal Info"]
        },
        "ORIG_ECAP_TRKR_NBR": {
            "Groups": ["Deal Info"]
        },
        "TOTAL_DOLLAR_AMOUNT": {
            "Groups": ["Deal Info"]
        },
        "ADJ_ECAP_UNIT": {
            "Groups": ["Deal Info"]
        },
        "MAX_PAYOUT": {
            "Groups": ["Deal Info"]
        }
    }
    
}