/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 9/6/2017 9:54:58 AM
Database Connection: EG1RDMDBDEV01\DEALSDEV,3180, MYDEALS
Machine Name: MHTIPPIN-MOBL
User: AMR\mhtippin
*/



using System;
using System.Runtime.Serialization;
using System.Collections.Generic;


namespace Intel.MyDeals.Entities {

	namespace meta {

		public struct ATRB_MSTR {

			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Primary Key
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: [smallint], Int16
			/// Max Length: 0
			///</summary>
			public const string DIM_SID = "DIM_SID";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			///</summary>
			public const string ATRB_COL_NM = "ATRB_COL_NM";


			///<summary>
			/// DataType: [varchar](255), String
			/// Max Length: 255
			///</summary>
			public const string ATRB_DESC = "ATRB_DESC";


			///<summary>
			/// DataType: [varchar](50), String
			/// Max Length: 50
			/// Nullable
			///</summary>
			public const string ATRB_LBL = "ATRB_LBL";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string DATA_TYPE_SID = "DATA_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string UI_TYPE_SID = "UI_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string LKUP_ROOT_SID = "LKUP_ROOT_SID";


			///<summary>
			/// DataType: [varchar](255), String
			/// Max Length: 255
			/// Nullable
			///</summary>
			public const string FRMT_MSK = "FRMT_MSK";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string ATRB_SRT_ORD = "ATRB_SRT_ORD";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string ATRB_UNIQ_IND = "ATRB_UNIQ_IND";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string ATRB_MAX_LEN = "ATRB_MAX_LEN";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string IS_IDX = "IS_IDX";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string PIVOT_MSK = "PIVOT_MSK";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string KEY_AT_ATRB_SID = "KEY_AT_ATRB_SID";


			///<summary>
			/// DataType: [varchar](20), String
			/// Max Length: 20
			/// Nullable
			///</summary>
			public const string ATRB_SRC_TBL_SCHMA = "ATRB_SRC_TBL_SCHMA";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_TBL_NM = "ATRB_SRC_TBL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_COL_NM = "ATRB_SRC_COL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_COL_SID = "ATRB_SRC_COL_SID";


			///<summary>
			/// DataType: [char](3), String
			/// Max Length: 3
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_SCHMA = "ATRB_FK_TBL_SCHMA";


			///<summary>
			/// DataType: [varchar](30), String
			/// Max Length: 30
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_NM = "ATRB_FK_TBL_NM";


			///<summary>
			/// DataType: [varchar](30), String
			/// Max Length: 30
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_PK_COL_NM = "ATRB_FK_TBL_PK_COL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_DSPLY_COL_NM = "ATRB_FK_TBL_DSPLY_COL_NM";


			///<summary>
			/// DataType: [varchar](80), String
			/// Max Length: 80
			/// Nullable
			///</summary>
			public const string ATRB_UNIQ_LEVELS = "ATRB_UNIQ_LEVELS";


			///<summary>
			/// DataType: [varchar](4000), String
			/// Max Length: 4000
			/// Nullable
			///</summary>
			public const string ATRB_EXT_PRO = "ATRB_EXT_PRO";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string ACTV_IND = "ACTV_IND";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CRE_EMP_WWID = "CRE_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CRE_DTM = "CRE_DTM";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CHG_EMP_WWID = "CHG_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CHG_DTM = "CHG_DTM";


			///<summary>
			/// DataType: [varchar](20), String
			/// Max Length: 20
			/// Nullable
			///</summary>
			public const string RLSE_ID = "RLSE_ID";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string POST_PRCSS_FLAG = "POST_PRCSS_FLAG";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string COST_TST_SCRN_FLAG = "COST_TST_SCRN_FLAG";


			///<summary>
			/// DataType: [varchar](256), String
			/// Max Length: 256
			/// Nullable
			///</summary>
			public const string atrb_cd = "atrb_cd";


			///<summary>
			/// DataType: [varchar](30), String
			/// Max Length: 30
			/// Nullable
			///</summary>
			public const string MJR_MNR_CHG = "MJR_MNR_CHG";

		}
	}

	namespace deal {

		public struct MYDL_CL_WIP_ATRB_TMP {

			///<summary>
			/// DataType: [uniqueidentifier], Guid
			/// Max Length: 0
			///</summary>
			public const string BTCH_ID = "BTCH_ID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CUST_MBR_SID = "CUST_MBR_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string OBJ_TYPE_SID = "OBJ_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string OBJ_SID = "OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string PARNT_OBJ_TYPE_SID = "PARNT_OBJ_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string PARNT_OBJ_SID = "PARNT_OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_MTX_HASH = "ATRB_MTX_HASH";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_MTX_SID = "ATRB_MTX_SID";


			///<summary>
			/// DataType: [varchar](8000), String
			/// Max Length: 8000
			/// Nullable
			///</summary>
			public const string ATRB_VAL = "ATRB_VAL";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_RVS_NBR = "ATRB_RVS_NBR";


			///<summary>
			/// DataType: [char](1), String
			/// Max Length: 1
			/// Nullable
			///</summary>
			public const string MDX_CD = "MDX_CD";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CHG_EMP_WWID = "CHG_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CHG_DTM = "CHG_DTM";


			///<summary>
			/// DataType: [varchar](-1), String
			/// Max Length: -1
			/// Nullable
			///</summary>
			public const string ATRB_VAL_MAX = "ATRB_VAL_MAX";

		}

		public struct MYDL_CL_WIP_ACTN {

			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Primary Key
			///</summary>
			public const string WIP_ACTN_SID = "WIP_ACTN_SID";


			///<summary>
			/// DataType: [uniqueidentifier], Guid
			/// Max Length: 0
			///</summary>
			public const string BTCH_ID = "BTCH_ID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string OBJ_TYPE_SID = "OBJ_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string OBJ_SID = "OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string OLD_OBJ_SID = "OLD_OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string SRT_ORD = "SRT_ORD";


			///<summary>
			/// DataType: [varchar](50), String
			/// Max Length: 50
			///</summary>
			public const string ACTN_NM = "ACTN_NM";


			///<summary>
			/// DataType: [varchar](500), String
			/// Max Length: 500
			/// Nullable
			///</summary>
			public const string MSG_CD = "MSG_CD";


			///<summary>
			/// DataType: [varchar](-1), String
			/// Max Length: -1
			/// Nullable
			///</summary>
			public const string ACTN_VAL_LIST = "ACTN_VAL_LIST";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CHG_EMP_WWID = "CHG_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CHG_DTM = "CHG_DTM";

		}

		public struct MYDL_CL_WIP_ATRB {

			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Primary Key
			///</summary>
			public const string WIP_ATRB_SID = "WIP_ATRB_SID";


			///<summary>
			/// DataType: [uniqueidentifier], Guid
			/// Max Length: 0
			///</summary>
			public const string BTCH_ID = "BTCH_ID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CUST_MBR_SID = "CUST_MBR_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string OBJ_TYPE_SID = "OBJ_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string OBJ_SID = "OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string PARNT_OBJ_TYPE_SID = "PARNT_OBJ_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string PARNT_OBJ_SID = "PARNT_OBJ_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_MTX_SID = "ATRB_MTX_SID";


			///<summary>
			/// DataType: [varchar](8000), String
			/// Max Length: 8000
			/// Nullable
			///</summary>
			public const string ATRB_VAL = "ATRB_VAL";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string ATRB_RVS_NBR = "ATRB_RVS_NBR";


			///<summary>
			/// DataType: [char](1), String
			/// Max Length: 1
			/// Nullable
			///</summary>
			public const string MDX_CD = "MDX_CD";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CHG_EMP_WWID = "CHG_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CHG_DTM = "CHG_DTM";


			///<summary>
			/// DataType: [varchar](-1), String
			/// Max Length: -1
			/// Nullable
			///</summary>
			public const string ATRB_VAL_MAX = "ATRB_VAL_MAX";

		}
	}

	namespace deal {

		public struct DEAL {

			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string CUST_MBR_SID = "CUST_MBR_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_TYPE_SID = "OBJ_TYPE_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_SID = "OBJ_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string PARNT_OBJ_TYPE_SID = "PARNT_OBJ_TYPE_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string PARNT_OBJ_SID = "PARNT_OBJ_SID";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string OBJ_TYPE = "OBJ_TYPE";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_RVS_NBR = "ATRB_RVS_NBR";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_MTX_SID = "ATRB_MTX_SID";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL = "ATRB_VAL";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string ATRB_MTX_HASH = "ATRB_MTX_HASH";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string ATRB_COL_NM = "ATRB_COL_NM";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string DOT_NET_DATA_TYPE = "DOT_NET_DATA_TYPE";


			///<summary>
			/// DataType: System.String
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_MAX = "ATRB_VAL_MAX";

		}
	}
}
