/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 1/11/2017 4:43:17 PM
Database Connection: EG1RDMDBDEV01\DEALSDEV,3180, MYDEALS
Machine Name: MHTIPPIN-MOBL
User: AMR\mhtippin
*/



using System;
using System.Runtime.Serialization;
using System.Collections.Generic;


namespace Intel.MyDeals.Entities {

	namespace dbo {

		public struct ATRB_MSTR {

			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Primary Key
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: [smallint], Int16
			/// Max Length: 0
			/// Primary Key
			///</summary>
			public const string DIM_SID = "DIM_SID";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			///</summary>
			public const string ATRB_COL_NM = "ATRB_COL_NM";


			///<summary>
			/// DataType: [varchar](255), String
			/// Max Length: 255
			///</summary>
			public const string ATRB_DESC = "ATRB_DESC";


			///<summary>
			/// DataType: [varchar](50), String
			/// Max Length: 50
			/// Nullable
			///</summary>
			public const string ATRB_LBL = "ATRB_LBL";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string DATA_TYPE_SID = "DATA_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string UI_TYPE_SID = "UI_TYPE_SID";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string LKUP_ROOT_SID = "LKUP_ROOT_SID";


			///<summary>
			/// DataType: [varchar](255), String
			/// Max Length: 255
			/// Nullable
			///</summary>
			public const string FRMT_MSK = "FRMT_MSK";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string ATRB_SRT_ORD = "ATRB_SRT_ORD";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string ATRB_UNIQ_IND = "ATRB_UNIQ_IND";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string ATRB_MAX_LEN = "ATRB_MAX_LEN";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string IS_FACT = "IS_FACT";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string IS_IDX = "IS_IDX";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string PIVOT_MSK = "PIVOT_MSK";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string KEY_AT_ATRB_SID = "KEY_AT_ATRB_SID";


			///<summary>
			/// DataType: [varchar](20), String
			/// Max Length: 20
			/// Nullable
			///</summary>
			public const string ATRB_SRC_TBL_SCHMA = "ATRB_SRC_TBL_SCHMA";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_TBL_NM = "ATRB_SRC_TBL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_COL_NM = "ATRB_SRC_COL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_SRC_COL_SID = "ATRB_SRC_COL_SID";


			///<summary>
			/// DataType: [char](3), String
			/// Max Length: 3
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_SCHMA = "ATRB_FK_TBL_SCHMA";


			///<summary>
			/// DataType: [varchar](30), String
			/// Max Length: 30
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_NM = "ATRB_FK_TBL_NM";


			///<summary>
			/// DataType: [varchar](30), String
			/// Max Length: 30
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_PK_COL_NM = "ATRB_FK_TBL_PK_COL_NM";


			///<summary>
			/// DataType: [varchar](100), String
			/// Max Length: 100
			/// Nullable
			///</summary>
			public const string ATRB_FK_TBL_DSPLY_COL_NM = "ATRB_FK_TBL_DSPLY_COL_NM";


			///<summary>
			/// DataType: [varchar](80), String
			/// Max Length: 80
			/// Nullable
			///</summary>
			public const string ATRB_UNIQ_LEVELS = "ATRB_UNIQ_LEVELS";


			///<summary>
			/// DataType: [varchar](4000), String
			/// Max Length: 4000
			/// Nullable
			///</summary>
			public const string ATRB_EXT_PRO = "ATRB_EXT_PRO";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			///</summary>
			public const string ACTV_IND = "ACTV_IND";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CRE_EMP_WWID = "CRE_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CRE_DTM = "CRE_DTM";


			///<summary>
			/// DataType: [int], Int32
			/// Max Length: 0
			///</summary>
			public const string CHG_EMP_WWID = "CHG_EMP_WWID";


			///<summary>
			/// DataType: [datetime], DateTime
			/// Max Length: 0
			///</summary>
			public const string CHG_DTM = "CHG_DTM";


			///<summary>
			/// DataType: [varchar](20), String
			/// Max Length: 20
			/// Nullable
			///</summary>
			public const string RLSE_ID = "RLSE_ID";


			///<summary>
			/// DataType: [bit], Boolean
			/// Max Length: 0
			/// Nullable
			///</summary>
			public const string POST_PRCSS_FLG = "POST_PRCSS_FLG";

		}
	}

	namespace deal {

		public struct DEAL {

			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_SET = "OBJ_SET";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_SID = "OBJ_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_PARENT_SID = "OBJ_PARENT_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_SID = "ATRB_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_CD = "ATRB_CD";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string DOT_NET_DATA_TYPE = "DOT_NET_DATA_TYPE";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_MTX_SID = "ATRB_MTX_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string OBJ_ATRB_SID = "OBJ_ATRB_SID";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_INT = "ATRB_VAL_INT";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_MONEY = "ATRB_VAL_MONEY";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_DTM = "ATRB_VAL_DTM";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_CHAR = "ATRB_VAL_CHAR";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_VAL_CHAR_MAX = "ATRB_VAL_CHAR_MAX";


			///<summary>
			/// DataType: System.Int32
			/// Max Length: -1
			///</summary>
			public const string ATRB_MTX_HASH = "ATRB_MTX_HASH";

		}
	}
}
