/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 7/1/2020 8:42:49 AM
Database Connection: EG1RDMDBITT01.amr.corp.intel.com\RDMITT1,3180, MYDEALS
Machine Name: MHTIPPIN-MOBL
User: AMR\mhtippin
*/



using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace Intel.MyDeals.Entities {

	[DataContract]
	public partial class MyDealsAttribute {


		[DataMember]
		public Int16 DIM_SID {set;get;}

		[DataMember]
		public Int32 ATRB_SID {set;get;}

		[DataMember]
		public String DIM_CD {set;get;}

		[DataMember]
		public String ATRB_COL_NM {set;get;}

		[DataMember]
		public String DATA_TYPE_CD {set;get;}

		[DataMember]
		public String UI_TYPE_CD {set;get;}

		[DataMember]
		public String ATRB_DESC {set;get;}

		[DataMember]
		public String ATRB_LBL {set;get;}

		[DataMember]
		public String DOT_NET_DATA_TYPE {set;get;}

		[DataMember]
		public String TGT_COL_TYPE {set;get;}

		[DataMember]
		public String FRMT_MSK {set;get;}

		[DataMember]
		public Int32 ATRB_SRT_ORD {set;get;}

		[DataMember]
		public Int32 ATRB_MAX_LEN {set;get;}

		[DataMember]
		public Int32 PIVOT_MSK {set;get;}

		[DataMember]
		public String MJR_MNR_CHG {set;get;}

		[DataMember]
		public Int32 ACTV_IND {set;get;}
	}
	public class MyDealsAttributeHelper
	{
		private struct PVT_MSK_CONST
		{

		};
		public static readonly Dictionary<int, string> ATTRIBUTE_PIVOT_MASK_MAP = new Dictionary<int, string>
		{

		};
	}
}
