/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 10/5/2016 9:53:45 AM
Database Connection: VMIDMSDVDB01\CP1CIAS,3181, CDMS_MYDEALS
Machine Name: PWECKENR-MOBL5
User: AMR\pweckenr
*/



using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace Intel.MyDeals.Entities {

	[DataContract]
	public partial class MyDealsAttribute {


		[DataMember]
		public Int16 DIM_SID {set;get;}

		[DataMember]
		public Int32 ATRB_SID { get; set; }

	    [DataMember]
		public String DIM_CD {set;get;}

		[DataMember]
		public String ATRB_CD {set;get;}

		[DataMember]
		public String DATA_TYPE_CD {set;get;}

		[DataMember]
		public String UI_TYPE_CD {set;get;}

		[DataMember]
		public String ATRB_DESC {set;get;}

		[DataMember]
		public String ATRB_LBL {set;get;}

		[DataMember]
		public String DOT_NET_DATA_TYPE {set;get;}

		[DataMember]
		public String TGT_COL_TYPE {set;get;}

		[DataMember]
		public String FMT_MSK {set;get;}

		[DataMember]
		public Int32 ATRB_SRT_ORD {set;get;}

		[DataMember]
		public Int32 ATRB_MAX_LEN {set;get;}

		[DataMember]
		public Boolean IS_FACT {set;get;}

		[DataMember]
		public Int32 PVT_MSK {set;get;}

		[DataMember]
		public Boolean ACTV_IND {set;get;}
	}
	public class DcsAttributeHelper
	{
		private struct PVT_MSK_CONST
		{
			public const int tdeal_PRD_LINE_AGRMNT_ATRB_PVT = 1;
			public const int tdeal_DEAL_PREP_ATRB_PVT = 2;
			public const int tdeal_DEAL_ATRB_PVT = 4;
			public const int tdeal_DEAL_ATRB_PVT_SNAPSHOT = 8;
			public const int tdeal_DEAL_ATRB_PVT_ARCHV = 16;
			public const int tdeal_DEAL_ATRB_MTX = 64;
		};
		public static readonly Dictionary<int, string> ATTRIBUTE_PIVOT_MASK_MAP = new Dictionary<int, string>
		{
			{PVT_MSK_CONST.tdeal_PRD_LINE_AGRMNT_ATRB_PVT,"tdeal_PRD_LINE_AGRMNT_ATRB_PVT"},
			{PVT_MSK_CONST.tdeal_DEAL_PREP_ATRB_PVT,"tdeal_DEAL_PREP_ATRB_PVT"},
			{PVT_MSK_CONST.tdeal_DEAL_ATRB_PVT,"tdeal_DEAL_ATRB_PVT"},
			{PVT_MSK_CONST.tdeal_DEAL_ATRB_PVT_SNAPSHOT,"tdeal_DEAL_ATRB_PVT_SNAPSHOT"},
			{PVT_MSK_CONST.tdeal_DEAL_ATRB_PVT_ARCHV,"tdeal_DEAL_ATRB_PVT_ARCHV"},
			{PVT_MSK_CONST.tdeal_DEAL_ATRB_MTX,"tdeal_DEAL_ATRB_MTX"}
		};
	}
}
