
/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 10/5/2016 9:54:14 AM
Database Connection: VMSDDDM001\CP1CIAS,3181, CDMS
Machine Name: PWECKENR-MOBL5
User: AMR\pweckenr
*/



using System;
using System.Linq;
using Intel.Opaque.Data;
using Intel.Opaque.Tools;


namespace Intel.MyDeals.Entities {

	internal static class KeyWraperConst {

		// Values used for DIM KEYS
		public const int PRD_BUCKT_SID_ATRB_SID = 5003;
		public const int WORKBOOK_ID_ATRB_SID = 5008;
		public const int GEO_MBR_SID_ATRB_SID = 5002;

		// Values used for ATRB MultiDim Getters
		public const int CAP_ATRB_SID = 86;
		public const int ECAP_PRICE_ATRB_SID = 5;

	} // KeyWraperConst

	//------------------------------------------------------------------------------------------------


	public partial class CAPKeyWrapper {

		private OpDataElementAtrb Deal;

		public CAPKeyWrapper(OpDataElementAtrb atrb)
		{
			if (atrb == null || atrb.DimKey == null){
				throw new NullReferenceException("Invalid attribute for use with multi-dimensional wrapper.");
			}
			Deal = atrb;
		}
		
		public System.String Value
		{
		    get
		    {
		        if (Deal.AtrbValue == null) // TODO:Check for castable to target type?
		        {
		            return default(System.String);
		        }
		        else
		        {
		            return (System.String)Deal.AtrbValue;
		        }
		    }
		    set
		    {
		        // What about 0 and deleting vlaues?
		        Deal.AtrbValue = value;
		    }
		}

		
		public int PRD_BUCKT_SID
		{
		    set 
		    {
		        Deal.DimKey.Set(KeyWraperConst.PRD_BUCKT_SID_ATRB_SID, value);
		    }
		    get 
		    {
		        return Deal.DimKey.GetDistinctDimKeyValue(KeyWraperConst.PRD_BUCKT_SID_ATRB_SID, 0);
		    }
		
		}

		
		public int WORKBOOK_ID
		{
		    set 
		    {
		        Deal.DimKey.Set(KeyWraperConst.WORKBOOK_ID_ATRB_SID, value);
		    }
		    get 
		    {
		        return Deal.DimKey.GetDistinctDimKeyValue(KeyWraperConst.WORKBOOK_ID_ATRB_SID, 0);
		    }
		
		}

		public string ToDealAtrbMatrixHash(){return String.Format("5003:{0}/5008:{1}", PRD_BUCKT_SID,WORKBOOK_ID);
		}
		public override string ToString(){return String.Format("{0} @ {1}", Value, ToDealAtrbMatrixHash());
		}
	} // CAPKeyWrapper


	public partial class ECAP_PRICEKeyWrapper {

		private OpDataElementAtrb Deal;

		public ECAP_PRICEKeyWrapper(OpDataElementAtrb atrb)
		{
			if (atrb == null || atrb.DimKey == null){
				throw new NullReferenceException("Invalid attribute for use with multi-dimensional wrapper.");
			}
			Deal = atrb;
		}
		
		public System.Double Value
		{
		    get
		    {
		        if (Deal.AtrbValue == null) // TODO:Check for castable to target type?
		        {
		            return default(System.Double);
		        }
		        else
		        {
		            return (System.Double)Deal.AtrbValue;
		        }
		    }
		    set
		    {
		        // What about 0 and deleting vlaues?
		        Deal.AtrbValue = value;
		    }
		}

		
		public int GEO_MBR_SID
		{
		    set 
		    {
		        Deal.DimKey.Set(KeyWraperConst.GEO_MBR_SID_ATRB_SID, value);
		    }
		    get 
		    {
		        return Deal.DimKey.GetDistinctDimKeyValue(KeyWraperConst.GEO_MBR_SID_ATRB_SID, 0);
		    }
		
		}

		
		public int PRD_BUCKT_SID
		{
		    set 
		    {
		        Deal.DimKey.Set(KeyWraperConst.PRD_BUCKT_SID_ATRB_SID, value);
		    }
		    get 
		    {
		        return Deal.DimKey.GetDistinctDimKeyValue(KeyWraperConst.PRD_BUCKT_SID_ATRB_SID, 0);
		    }
		
		}

		public string ToDealAtrbMatrixHash(){return String.Format("5002:{0}/5003:{1}", GEO_MBR_SID,PRD_BUCKT_SID);
		}
		public override string ToString(){return String.Format("{0} @ {1}", Value, ToDealAtrbMatrixHash());
		}
	} // ECAP_PRICEKeyWrapper


	//------------------------------------------------------------------------------------------------

	public partial class DealPropertyWrapper {

		///<summary>
		/// Underlying deal and primary data repository
		///</summary>
		public OpDataCollector Deal {get; private set;}

		///<summary>
		/// When true, wrapper will cache values on first get.  When false, not cached.
		///</summary>
		private bool Caching {get; set;}

		///<summary>
		/// A wrapper around a deal to make accessing common properties easier
		///</summary>
		///<param name="deal">Deal data repository</param>
		///<param name="caching">When true, wrapper will cache data on first get, else no caching</param>
		public DealPropertyWrapper(OpDataCollector deal, bool caching = true)
		{
			if(deal == null){ throw new ArgumentException("deal"); }
			Deal = deal;
			Caching = caching;
		}

		///<summary>
		/// ID: 3459
		/// Max Len: 100
		/// Label:  "Consumption Reason"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string CONSUMPTION_REASON
		{
		    get
		    {
		        if (_CONSUMPTION_REASON == null)
		        {
					_CONSUMPTION_REASON = String.Format("{0}", Deal.GetDataElementValue("CONSUMPTION_REASON"));
		        }
		        return _CONSUMPTION_REASON ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("CONSUMPTION_REASON");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _CONSUMPTION_REASON = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _CONSUMPTION_REASON = null;


		///<summary>
		/// ID: 3011
		/// Max Len: 8
		/// Label:  "customer ID"
		/// SQL Type: [int]
		/// Col: ATRB_VAL_INT
		/// Format: {0:d}
		///</summary>
		public int CUST_MBR_SID
		{
		    get
		    {
		        if (!Caching || _CUST_MBR_SID == null)
		        {
					var av = Deal.GetDataElementValue("CUST_MBR_SID");
					int val;
					if(av != null && Int32.TryParse(av.ToString(), out val))
					{
						_CUST_MBR_SID = val;
					} else {
						_CUST_MBR_SID = default(int);
					}
		                    
		        }
		        return (int)_CUST_MBR_SID;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("CUST_MBR_SID");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _CUST_MBR_SID = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private int? _CUST_MBR_SID = null;


		///<summary>
		/// ID: 3594
		/// Max Len: 50
		/// Label:  "Additive"
		/// SQL Type: [varchar](50)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string DEAL_COMB_TYPE
		{
		    get
		    {
		        if (_DEAL_COMB_TYPE == null)
		        {
					_DEAL_COMB_TYPE = String.Format("{0}", Deal.GetDataElementValue("DEAL_COMB_TYPE"));
		        }
		        return _DEAL_COMB_TYPE ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("DEAL_COMB_TYPE");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _DEAL_COMB_TYPE = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _DEAL_COMB_TYPE = null;


		///<summary>
		/// ID: 3492
		/// Max Len: 255
		/// Label:  "Deal Program Type"
		/// SQL Type: [varchar](255)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string DEAL_PGM_TYPE
		{
		    get
		    {
		        if (_DEAL_PGM_TYPE == null)
		        {
					_DEAL_PGM_TYPE = String.Format("{0}", Deal.GetDataElementValue("DEAL_PGM_TYPE"));
		        }
		        return _DEAL_PGM_TYPE ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("DEAL_PGM_TYPE");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _DEAL_PGM_TYPE = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _DEAL_PGM_TYPE = null;


		///<summary>
		/// ID: 3327
		/// Max Len: 100
		/// Label:  "Current Stage"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string DEAL_STG_CD
		{
		    get
		    {
		        if (_DEAL_STG_CD == null)
		        {
					_DEAL_STG_CD = String.Format("{0}", Deal.GetDataElementValue("DEAL_STG_CD"));
		        }
		        return _DEAL_STG_CD ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("DEAL_STG_CD");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _DEAL_STG_CD = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _DEAL_STG_CD = null;


		///<summary>
		/// ID: 3004
		/// Max Len: 10
		/// Label:  "Deal Type Code ID"
		/// SQL Type: [int]
		/// Col: ATRB_VAL_INT
		/// Format: {0:d}
		///</summary>
		public int DEAL_TYPE_CD_SID
		{
		    get
		    {
		        if (!Caching || _DEAL_TYPE_CD_SID == null)
		        {
					var av = Deal.GetDataElementValue("DEAL_TYPE_CD_SID");
					int val;
					if(av != null && Int32.TryParse(av.ToString(), out val))
					{
						_DEAL_TYPE_CD_SID = val;
					} else {
						_DEAL_TYPE_CD_SID = default(int);
					}
		                    
		        }
		        return (int)_DEAL_TYPE_CD_SID;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("DEAL_TYPE_CD_SID");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _DEAL_TYPE_CD_SID = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private int? _DEAL_TYPE_CD_SID = null;


		///<summary>
		/// ID: 3331
		/// Max Len: 100
		/// Label:  "ECAP Type"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string ECAP_TYPE
		{
		    get
		    {
		        if (_ECAP_TYPE == null)
		        {
					_ECAP_TYPE = String.Format("{0}", Deal.GetDataElementValue("ECAP_TYPE"));
		        }
		        return _ECAP_TYPE ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("ECAP_TYPE");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _ECAP_TYPE = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _ECAP_TYPE = null;


		///<summary>
		/// ID: 3320
		/// Max Len: 0
		/// Label:  "End Date"
		/// SQL Type: [datetime]
		/// Col: ATRB_VAL_DTM
		/// Format: {0:MM/dd/yyyy HH:mm:ss.fff}
		///</summary>
		public DateTime END_DT
		{
		    get
		    {
		        if (!Caching || _END_DT == null)
		        {
					var av = Deal.GetDataElementValue("END_DT");
					DateTime val;
		
					if(av != null && DateTime.TryParse(av.ToString(), out val))
					{
						_END_DT = val;
					} else {
						_END_DT = OpaqueConst.SQL_MIN_DATE;
					}
		                    
		        }
		        return (DateTime)_END_DT;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("END_DT");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _END_DT = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private DateTime? _END_DT = null;


		///<summary>
		/// ID: 3465
		/// Max Len: 100
		/// Label:  "Standalone or KIT"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string KIT_CHK
		{
		    get
		    {
		        if (_KIT_CHK == null)
		        {
					_KIT_CHK = String.Format("{0}", Deal.GetDataElementValue("KIT_CHK"));
		        }
		        return _KIT_CHK ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("KIT_CHK");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _KIT_CHK = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _KIT_CHK = null;


		///<summary>
		/// ID: 3474
		/// Max Len: 100
		/// Label:  "Market Segment"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string MRKT_SEG_COMBINED
		{
		    get
		    {
		        if (_MRKT_SEG_COMBINED == null)
		        {
					_MRKT_SEG_COMBINED = String.Format("{0}", Deal.GetDataElementValue("MRKT_SEG_COMBINED"));
		        }
		        return _MRKT_SEG_COMBINED ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("MRKT_SEG_COMBINED");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _MRKT_SEG_COMBINED = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _MRKT_SEG_COMBINED = null;


		///<summary>
		/// ID: 3495
		/// Max Len: 100
		/// Label:  "Program Payment"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string PROGRAM_PAYMENT
		{
		    get
		    {
		        if (_PROGRAM_PAYMENT == null)
		        {
					_PROGRAM_PAYMENT = String.Format("{0}", Deal.GetDataElementValue("PROGRAM_PAYMENT"));
		        }
		        return _PROGRAM_PAYMENT ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("PROGRAM_PAYMENT");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _PROGRAM_PAYMENT = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _PROGRAM_PAYMENT = null;


		///<summary>
		/// ID: 3571
		/// Max Len: 0
		/// Label:  "Billing END Date (for Consumption)"
		/// SQL Type: [datetime]
		/// Col: ATRB_VAL_DTM
		/// Format: {0:MM/dd/yyyy HH:mm:ss.fff}
		///</summary>
		public DateTime REBATE_BILLING_END
		{
		    get
		    {
		        if (!Caching || _REBATE_BILLING_END == null)
		        {
					var av = Deal.GetDataElementValue("REBATE_BILLING_END");
					DateTime val;
		
					if(av != null && DateTime.TryParse(av.ToString(), out val))
					{
						_REBATE_BILLING_END = val;
					} else {
						_REBATE_BILLING_END = OpaqueConst.SQL_MIN_DATE;
					}
		                    
		        }
		        return (DateTime)_REBATE_BILLING_END;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("REBATE_BILLING_END");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _REBATE_BILLING_END = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private DateTime? _REBATE_BILLING_END = null;


		///<summary>
		/// ID: 3570
		/// Max Len: 0
		/// Label:  "Billing START Date (for Consumption)"
		/// SQL Type: [datetime]
		/// Col: ATRB_VAL_DTM
		/// Format: {0:MM/dd/yyyy HH:mm:ss.fff}
		///</summary>
		public DateTime REBATE_BILLING_START
		{
		    get
		    {
		        if (!Caching || _REBATE_BILLING_START == null)
		        {
					var av = Deal.GetDataElementValue("REBATE_BILLING_START");
					DateTime val;
		
					if(av != null && DateTime.TryParse(av.ToString(), out val))
					{
						_REBATE_BILLING_START = val;
					} else {
						_REBATE_BILLING_START = OpaqueConst.SQL_MIN_DATE;
					}
		                    
		        }
		        return (DateTime)_REBATE_BILLING_START;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("REBATE_BILLING_START");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _REBATE_BILLING_START = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private DateTime? _REBATE_BILLING_START = null;


		///<summary>
		/// ID: 3319
		/// Max Len: 0
		/// Label:  "Start Date"
		/// SQL Type: [datetime]
		/// Col: ATRB_VAL_DTM
		/// Format: {0:MM/dd/yyyy HH:mm:ss.fff}
		///</summary>
		public DateTime START_DT
		{
		    get
		    {
		        if (!Caching || _START_DT == null)
		        {
					var av = Deal.GetDataElementValue("START_DT");
					DateTime val;
		
					if(av != null && DateTime.TryParse(av.ToString(), out val))
					{
						_START_DT = val;
					} else {
						_START_DT = OpaqueConst.SQL_MIN_DATE;
					}
		                    
		        }
		        return (DateTime)_START_DT;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("START_DT");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _START_DT = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private DateTime? _START_DT = null;


		///<summary>
		/// ID: 3002
		/// Max Len: 100
		/// Label:  "Deal Type"
		/// SQL Type: [varchar](100)
		/// Col: ATRB_VAL_CHAR
		/// Format: {0}
		///</summary>
		public string DEAL_TYPE_CD
		{
		    get
		    {
		        if (_DEAL_TYPE_CD == null)
		        {
					_DEAL_TYPE_CD = String.Format("{0}", Deal.GetDataElementValue("DEAL_TYPE_CD"));
		        }
		        return _DEAL_TYPE_CD ?? String.Empty;
		    }
			
		set
		{
		    var atrb = Deal.GetDataElement("DEAL_TYPE_CD");
		    if (atrb != null)
		    {
		        atrb.AtrbValue = _DEAL_TYPE_CD = value; // Set both property and cache value, WARNING: AtrbValue can alter the set value causing issues here...
		    }
		}
		
		}
		private string _DEAL_TYPE_CD = null;

		
		///<summary>
		/// A collection of values and the variation paramter keys.
		///</summary>
		public OpPairList<int, CAPKeyWrapper> CAP
		{
		    get
		    {
		        var ret = new OpPairList<int, CAPKeyWrapper>();
		        foreach(OpDataElementAtrb oda in Deal.GetDataElements(KeyWraperConst.CAP_ATRB_SID.ToString()))
		        {
		            ret.Add(oda.ElementID, new CAPKeyWrapper(oda));
		        }
		        return ret;
		                
		    }
		}

		
		///<summary>
		/// A collection of values and the variation paramter keys.
		///</summary>
		public OpPairList<int, ECAP_PRICEKeyWrapper> ECAP_PRICE
		{
		    get
		    {
		        var ret = new OpPairList<int, ECAP_PRICEKeyWrapper>();
		        foreach(OpDataElementAtrb oda in Deal.GetDataElements(KeyWraperConst.ECAP_PRICE_ATRB_SID.ToString()))
		        {
		            ret.Add(oda.ElementID, new ECAP_PRICEKeyWrapper(oda));
		        }
		        return ret;
		                
		    }
		}

		///<summary>
		/// Clear all internal wrapper caches
		///</summary>
		///<param name="fields">When not set, clear all caches, else just clear for passed fields.</param>
		public void ResetCache(params string[] fields)
		{
			if(fields == null || !fields.Any(s=>!String.IsNullOrEmpty(s)))
			{
				_CONSUMPTION_REASON = String.Empty;
				_CUST_MBR_SID = null;
				_DEAL_COMB_TYPE = String.Empty;
				_DEAL_PGM_TYPE = String.Empty;
				_DEAL_STG_CD = String.Empty;
				_DEAL_TYPE_CD_SID = null;
				_ECAP_TYPE = String.Empty;
				_END_DT = null;
				_KIT_CHK = String.Empty;
				_MRKT_SEG_COMBINED = String.Empty;
				_PROGRAM_PAYMENT = String.Empty;
				_REBATE_BILLING_END = null;
				_REBATE_BILLING_START = null;
				_START_DT = null;
				_DEAL_TYPE_CD = String.Empty;
			} else {
				foreach(string f in fields)
				{
					switch(f)
					{
						case "CONSUMPTION_REASON": _CONSUMPTION_REASON = String.Empty; break;
						case "CUST_MBR_SID": _CUST_MBR_SID = null; break;
						case "DEAL_COMB_TYPE": _DEAL_COMB_TYPE = String.Empty; break;
						case "DEAL_PGM_TYPE": _DEAL_PGM_TYPE = String.Empty; break;
						case "DEAL_STG_CD": _DEAL_STG_CD = String.Empty; break;
						case "DEAL_TYPE_CD_SID": _DEAL_TYPE_CD_SID = null; break;
						case "ECAP_TYPE": _ECAP_TYPE = String.Empty; break;
						case "END_DT": _END_DT = null; break;
						case "KIT_CHK": _KIT_CHK = String.Empty; break;
						case "MRKT_SEG_COMBINED": _MRKT_SEG_COMBINED = String.Empty; break;
						case "PROGRAM_PAYMENT": _PROGRAM_PAYMENT = String.Empty; break;
						case "REBATE_BILLING_END": _REBATE_BILLING_END = null; break;
						case "REBATE_BILLING_START": _REBATE_BILLING_START = null; break;
						case "START_DT": _START_DT = null; break;
						case "DEAL_TYPE_CD": _DEAL_TYPE_CD = String.Empty; break;
					}
				}
			}
		}
		
		public override string ToString()
		{
		    return (Deal == null)
		        ? "Deal Not Set"
		        : Deal.ToString();
		}

	}
}
