/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 11/8/2016 10:28:32 AM
Database Connection: EG1RDMDBDEV01\DEALSDEV,3181, MyDeals
Machine Name: JAJUANG-MOBL3
User: AMR\jajuang
*/


using System;
using System.Runtime.Serialization;
using System.Collections.Generic;


namespace Intel.MyDeals.Entities {
	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:33 AM
	///</summary>
	
	[DataContract]
	public partial class PingResults {
	
	[DataMember]
	public System.String CDMS_DB_VERSION {set;get;}
	
	
	[DataMember]
	public System.String CI_BUILD_END {set;get;}
	
	
	[DataMember]
	public System.String DB_RESTORE_FROM_PROD_DATE {set;get;}
	
	
	[DataMember]
	public System.String DbEnv {set;get;}
	
	
	[DataMember]
	public System.String DbServer {set;get;}
	
	
	[DataMember]
	public System.String Source {set;get;}
	
	
	[DataMember]
	public Nullable<System.DateTime> TimeStamp {set;get;}
	
	
	/*
	private static List<PingResults> PingResultsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<PingResults>();
	int IDX_CDMS_DB_VERSION = DB.GetReaderOrdinal(rdr, "CDMS_DB_VERSION");
	int IDX_CI_BUILD_END = DB.GetReaderOrdinal(rdr, "CI_BUILD_END");
	int IDX_DB_RESTORE_FROM_PROD_DATE = DB.GetReaderOrdinal(rdr, "DB_RESTORE_FROM_PROD_DATE");
	int IDX_DbEnv = DB.GetReaderOrdinal(rdr, "DbEnv");
	int IDX_DbServer = DB.GetReaderOrdinal(rdr, "DbServer");
	int IDX_Source = DB.GetReaderOrdinal(rdr, "Source");
	int IDX_TimeStamp = DB.GetReaderOrdinal(rdr, "TimeStamp");
	
	while (rdr.Read()){
	ret.Add(new PingResults {
	CDMS_DB_VERSION = (IDX_CDMS_DB_VERSION < 0 || rdr.IsDBNull(IDX_CDMS_DB_VERSION)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CDMS_DB_VERSION),
	CI_BUILD_END = (IDX_CI_BUILD_END < 0 || rdr.IsDBNull(IDX_CI_BUILD_END)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CI_BUILD_END),
	DB_RESTORE_FROM_PROD_DATE = (IDX_DB_RESTORE_FROM_PROD_DATE < 0 || rdr.IsDBNull(IDX_DB_RESTORE_FROM_PROD_DATE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DB_RESTORE_FROM_PROD_DATE),
	DbEnv = (IDX_DbEnv < 0 || rdr.IsDBNull(IDX_DbEnv)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DbEnv),
	DbServer = (IDX_DbServer < 0 || rdr.IsDBNull(IDX_DbServer)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DbServer),
	Source = (IDX_Source < 0 || rdr.IsDBNull(IDX_Source)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_Source),
	TimeStamp = (IDX_TimeStamp < 0 || rdr.IsDBNull(IDX_TimeStamp)) ? default(Nullable<System.DateTime>) : rdr.GetFieldValue<Nullable<System.DateTime>>(IDX_TimeStamp)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class PingResults

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:33 AM
	///</summary>
	
	[DataContract]
	public partial class PocEmp {
	
	[DataMember]
	public Nullable<System.Int32> emp_sid {set;get;}
	
	
	[DataMember]
	public System.String first_nm {set;get;}
	
	
	[DataMember]
	public System.String last_nm {set;get;}
	
	
	/*
	private static List<PocEmp> PocEmpFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<PocEmp>();
	int IDX_emp_sid = DB.GetReaderOrdinal(rdr, "emp_sid");
	int IDX_first_nm = DB.GetReaderOrdinal(rdr, "first_nm");
	int IDX_last_nm = DB.GetReaderOrdinal(rdr, "last_nm");
	
	while (rdr.Read()){
	ret.Add(new PocEmp {
	emp_sid = (IDX_emp_sid < 0 || rdr.IsDBNull(IDX_emp_sid)) ? default(Nullable<System.Int32>) : rdr.GetFieldValue<Nullable<System.Int32>>(IDX_emp_sid),
	first_nm = (IDX_first_nm < 0 || rdr.IsDBNull(IDX_first_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_first_nm),
	last_nm = (IDX_last_nm < 0 || rdr.IsDBNull(IDX_last_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_last_nm)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class PocEmp

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:33 AM
	///</summary>
	
	[DataContract]
	public partial class ToolConstants {
	
	[DataMember]
	public System.String CNST_DESC {set;get;}
	
	
	[DataMember]
	public System.String CNST_NM {set;get;}
	
	
	[DataMember]
	public System.String CNST_VAL_TXT {set;get;}
	
	
	/*
	private static List<ToolConstants> ToolConstantsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<ToolConstants>();
	int IDX_CNST_DESC = DB.GetReaderOrdinal(rdr, "CNST_DESC");
	int IDX_CNST_NM = DB.GetReaderOrdinal(rdr, "CNST_NM");
	int IDX_CNST_VAL_TXT = DB.GetReaderOrdinal(rdr, "CNST_VAL_TXT");
	
	while (rdr.Read()){
	ret.Add(new ToolConstants {
	CNST_DESC = (IDX_CNST_DESC < 0 || rdr.IsDBNull(IDX_CNST_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_DESC),
	CNST_NM = (IDX_CNST_NM < 0 || rdr.IsDBNull(IDX_CNST_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_NM),
	CNST_VAL_TXT = (IDX_CNST_VAL_TXT < 0 || rdr.IsDBNull(IDX_CNST_VAL_TXT)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_VAL_TXT)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class ToolConstants

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:34 AM
	///</summary>
	
	[DataContract]
	public partial class AdminConstant {
	
	[DataMember]
	public System.String cnst_desc {set;get;}
	
	
	[DataMember]
	public System.String cnst_nm {set;get;}
	
	
	[DataMember]
	public System.Int32 cnst_sid {set;get;}
	
	
	[DataMember]
	public System.String cnst_val_txt {set;get;}
	
	
	[DataMember]
	public System.Boolean ui_updatable {set;get;}
	
	
	/*
	private static List<AdminConstant> AdminConstantFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminConstant>();
	int IDX_cnst_desc = DB.GetReaderOrdinal(rdr, "cnst_desc");
	int IDX_cnst_nm = DB.GetReaderOrdinal(rdr, "cnst_nm");
	int IDX_cnst_sid = DB.GetReaderOrdinal(rdr, "cnst_sid");
	int IDX_cnst_val_txt = DB.GetReaderOrdinal(rdr, "cnst_val_txt");
	int IDX_ui_updatable = DB.GetReaderOrdinal(rdr, "ui_updatable");
	
	while (rdr.Read()){
	ret.Add(new AdminConstant {
	cnst_desc = (IDX_cnst_desc < 0 || rdr.IsDBNull(IDX_cnst_desc)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_cnst_desc),
	cnst_nm = (IDX_cnst_nm < 0 || rdr.IsDBNull(IDX_cnst_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_cnst_nm),
	cnst_sid = (IDX_cnst_sid < 0 || rdr.IsDBNull(IDX_cnst_sid)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_cnst_sid),
	cnst_val_txt = (IDX_cnst_val_txt < 0 || rdr.IsDBNull(IDX_cnst_val_txt)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_cnst_val_txt),
	ui_updatable = (IDX_ui_updatable < 0 || rdr.IsDBNull(IDX_ui_updatable)) ? default(System.Boolean) : ((int)rdr[IDX_ui_updatable] == 1)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminConstant

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:34 AM
	///</summary>
	
	[DataContract]
	public partial class AdminApplications {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.String APPL_CD {set;get;}
	
	
	[DataMember]
	public System.String APPL_DESC {set;get;}
	
	
	[DataMember]
	public System.Byte APPL_SID {set;get;}
	
	
	[DataMember]
	public System.String APPL_SUITE {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	/*
	private static List<AdminApplications> AdminApplicationsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminApplications>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_APPL_CD = DB.GetReaderOrdinal(rdr, "APPL_CD");
	int IDX_APPL_DESC = DB.GetReaderOrdinal(rdr, "APPL_DESC");
	int IDX_APPL_SID = DB.GetReaderOrdinal(rdr, "APPL_SID");
	int IDX_APPL_SUITE = DB.GetReaderOrdinal(rdr, "APPL_SUITE");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	
	while (rdr.Read()){
	ret.Add(new AdminApplications {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : ((int)rdr[IDX_ACTV_IND] == 1),
	APPL_CD = (IDX_APPL_CD < 0 || rdr.IsDBNull(IDX_APPL_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APPL_CD),
	APPL_DESC = (IDX_APPL_DESC < 0 || rdr.IsDBNull(IDX_APPL_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APPL_DESC),
	APPL_SID = (IDX_APPL_SID < 0 || rdr.IsDBNull(IDX_APPL_SID)) ? default(System.Byte) : rdr.GetFieldValue<System.Byte>(IDX_APPL_SID),
	APPL_SUITE = (IDX_APPL_SUITE < 0 || rdr.IsDBNull(IDX_APPL_SUITE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APPL_SUITE),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminApplications

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:34 AM
	///</summary>
	
	[DataContract]
	public partial class AdminDealType {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Int32 DEAL_ATRB_SID {set;get;}
	
	
	[DataMember]
	public System.String DEAL_TYPE_CD {set;get;}
	
	
	[DataMember]
	public System.String DEAL_TYPE_DESC {set;get;}
	
	
	[DataMember]
	public System.Int32 DEAL_TYPE_SID {set;get;}
	
	
	[DataMember]
	public System.Boolean PERFORM_CTST {set;get;}
	
	
	[DataMember]
	public System.Int32 TEMPLT_DEAL_NBR {set;get;}
	
	
	[DataMember]
	public System.Int32 TEMPLT_DEAL_SID {set;get;}
	
	
	[DataMember]
	public System.String TRKR_NBR_DT_LTR {set;get;}
	
	
	/*
	private static List<AdminDealType> AdminDealTypeFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminDealType>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_DEAL_ATRB_SID = DB.GetReaderOrdinal(rdr, "DEAL_ATRB_SID");
	int IDX_DEAL_TYPE_CD = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_CD");
	int IDX_DEAL_TYPE_DESC = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_DESC");
	int IDX_DEAL_TYPE_SID = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_SID");
	int IDX_PERFORM_CTST = DB.GetReaderOrdinal(rdr, "PERFORM_CTST");
	int IDX_TEMPLT_DEAL_NBR = DB.GetReaderOrdinal(rdr, "TEMPLT_DEAL_NBR");
	int IDX_TEMPLT_DEAL_SID = DB.GetReaderOrdinal(rdr, "TEMPLT_DEAL_SID");
	int IDX_TRKR_NBR_DT_LTR = DB.GetReaderOrdinal(rdr, "TRKR_NBR_DT_LTR");
	
	while (rdr.Read()){
	ret.Add(new AdminDealType {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : ((int)rdr[IDX_ACTV_IND] == 1),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	DEAL_ATRB_SID = (IDX_DEAL_ATRB_SID < 0 || rdr.IsDBNull(IDX_DEAL_ATRB_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_DEAL_ATRB_SID),
	DEAL_TYPE_CD = (IDX_DEAL_TYPE_CD < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DEAL_TYPE_CD),
	DEAL_TYPE_DESC = (IDX_DEAL_TYPE_DESC < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DEAL_TYPE_DESC),
	DEAL_TYPE_SID = (IDX_DEAL_TYPE_SID < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_DEAL_TYPE_SID),
	PERFORM_CTST = (IDX_PERFORM_CTST < 0 || rdr.IsDBNull(IDX_PERFORM_CTST)) ? default(System.Boolean) : ((int)rdr[IDX_PERFORM_CTST] == 1),
	TEMPLT_DEAL_NBR = (IDX_TEMPLT_DEAL_NBR < 0 || rdr.IsDBNull(IDX_TEMPLT_DEAL_NBR)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_TEMPLT_DEAL_NBR),
	TEMPLT_DEAL_SID = (IDX_TEMPLT_DEAL_SID < 0 || rdr.IsDBNull(IDX_TEMPLT_DEAL_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_TEMPLT_DEAL_SID),
	TRKR_NBR_DT_LTR = (IDX_TRKR_NBR_DT_LTR < 0 || rdr.IsDBNull(IDX_TRKR_NBR_DT_LTR)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_TRKR_NBR_DT_LTR)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminDealType

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:35 AM
	///</summary>
	
	[DataContract]
	public partial class AdminRoleType {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.Byte APPL_SID {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Boolean IS_SINGLE_SELECT {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TIER_CD {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_CD {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_DESC {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_DSPLY_CD {set;get;}
	
	
	[DataMember]
	public System.Int32 ROLE_TYPE_SID {set;get;}
	
	
	/*
	private static List<AdminRoleType> AdminRoleTypeFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminRoleType>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_APPL_SID = DB.GetReaderOrdinal(rdr, "APPL_SID");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_IS_SINGLE_SELECT = DB.GetReaderOrdinal(rdr, "IS_SINGLE_SELECT");
	int IDX_ROLE_TIER_CD = DB.GetReaderOrdinal(rdr, "ROLE_TIER_CD");
	int IDX_ROLE_TYPE_CD = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_CD");
	int IDX_ROLE_TYPE_DESC = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_DESC");
	int IDX_ROLE_TYPE_DSPLY_CD = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_DSPLY_CD");
	int IDX_ROLE_TYPE_SID = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_SID");
	
	while (rdr.Read()){
	ret.Add(new AdminRoleType {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : ((int)rdr[IDX_ACTV_IND] == 1),
	APPL_SID = (IDX_APPL_SID < 0 || rdr.IsDBNull(IDX_APPL_SID)) ? default(System.Byte) : rdr.GetFieldValue<System.Byte>(IDX_APPL_SID),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	IS_SINGLE_SELECT = (IDX_IS_SINGLE_SELECT < 0 || rdr.IsDBNull(IDX_IS_SINGLE_SELECT)) ? default(System.Boolean) : ((int)rdr[IDX_IS_SINGLE_SELECT] == 1),
	ROLE_TIER_CD = (IDX_ROLE_TIER_CD < 0 || rdr.IsDBNull(IDX_ROLE_TIER_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TIER_CD),
	ROLE_TYPE_CD = (IDX_ROLE_TYPE_CD < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_CD),
	ROLE_TYPE_DESC = (IDX_ROLE_TYPE_DESC < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_DESC),
	ROLE_TYPE_DSPLY_CD = (IDX_ROLE_TYPE_DSPLY_CD < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_DSPLY_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_DSPLY_CD),
	ROLE_TYPE_SID = (IDX_ROLE_TYPE_SID < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ROLE_TYPE_SID)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminRoleType

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:35 AM
	///</summary>
	
	[DataContract]
	public partial class SecurityActions {
	
	[DataMember]
	public System.String ACTN_CATGRY_CD {set;get;}
	
	
	[DataMember]
	public System.String ACTN_CD {set;get;}
	
	
	[DataMember]
	public System.String ACTN_DESC {set;get;}
	
	
	[DataMember]
	public System.Int32 ACTN_SID {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Int32 SRT_ORD {set;get;}
	
	
	[DataMember]
	public System.String WFSTG_ACTN_CD {set;get;}
	
	
	/*
	private static List<SecurityActions> SecurityActionsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<SecurityActions>();
	int IDX_ACTN_CATGRY_CD = DB.GetReaderOrdinal(rdr, "ACTN_CATGRY_CD");
	int IDX_ACTN_CD = DB.GetReaderOrdinal(rdr, "ACTN_CD");
	int IDX_ACTN_DESC = DB.GetReaderOrdinal(rdr, "ACTN_DESC");
	int IDX_ACTN_SID = DB.GetReaderOrdinal(rdr, "ACTN_SID");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_SRT_ORD = DB.GetReaderOrdinal(rdr, "SRT_ORD");
	int IDX_WFSTG_ACTN_CD = DB.GetReaderOrdinal(rdr, "WFSTG_ACTN_CD");
	
	while (rdr.Read()){
	ret.Add(new SecurityActions {
	ACTN_CATGRY_CD = (IDX_ACTN_CATGRY_CD < 0 || rdr.IsDBNull(IDX_ACTN_CATGRY_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_CATGRY_CD),
	ACTN_CD = (IDX_ACTN_CD < 0 || rdr.IsDBNull(IDX_ACTN_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_CD),
	ACTN_DESC = (IDX_ACTN_DESC < 0 || rdr.IsDBNull(IDX_ACTN_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_DESC),
	ACTN_SID = (IDX_ACTN_SID < 0 || rdr.IsDBNull(IDX_ACTN_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ACTN_SID),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	SRT_ORD = (IDX_SRT_ORD < 0 || rdr.IsDBNull(IDX_SRT_ORD)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_SRT_ORD),
	WFSTG_ACTN_CD = (IDX_WFSTG_ACTN_CD < 0 || rdr.IsDBNull(IDX_WFSTG_ACTN_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_WFSTG_ACTN_CD)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class SecurityActions

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JAJUANG-MOBL3
	/// by jajuang
	/// at 11/8/2016 10:28:35 AM
	///</summary>
	
	[DataContract]
	public partial class LogConfig {
	
	[DataMember]
	public System.Boolean IsActive {set;get;}
	
	
	[DataMember]
	public System.String MsgSrc {set;get;}
	
	
	/*
	private static List<LogConfig> LogConfigFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<LogConfig>();
	int IDX_IsActive = DB.GetReaderOrdinal(rdr, "IsActive");
	int IDX_MsgSrc = DB.GetReaderOrdinal(rdr, "MsgSrc");
	
	while (rdr.Read()){
	ret.Add(new LogConfig {
	IsActive = (IDX_IsActive < 0 || rdr.IsDBNull(IDX_IsActive)) ? default(System.Boolean) : ((int)rdr[IDX_IsActive] == 1),
	MsgSrc = (IDX_MsgSrc < 0 || rdr.IsDBNull(IDX_MsgSrc)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_MsgSrc)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class LogConfig

}
