/*
*** DO NOT MODIFY THIS FILE ***
This file is auto generated by a custom T4 template.
To change structures within this file, alter the source template (*.tt file).
To extend objects within this file, create partial or super classes in other files.

Modified: 11/30/2016 2:09:48 PM
Database Connection: EG1RDMDBDEV01\DEALSDEV,3180, MyDeals
Machine Name: JJYEH-MOBL
User: AMR\jjyeh
*/


using System;
using System.Runtime.Serialization;
using System.Collections.Generic;


namespace Intel.MyDeals.Entities {
	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class PingResults {
	
	[DataMember]
	public System.String CDMS_DB_VERSION {set;get;}
	
	
	[DataMember]
	public System.String CI_BUILD_END {set;get;}
	
	
	[DataMember]
	public System.String DB_RESTORE_FROM_PROD_DATE {set;get;}
	
	
	[DataMember]
	public System.String DbEnv {set;get;}
	
	
	[DataMember]
	public System.String DbServer {set;get;}
	
	
	[DataMember]
	public System.String Source {set;get;}
	
	
	[DataMember]
	public Nullable<System.DateTime> TimeStamp {set;get;}
	
	
	/*
	private static List<PingResults> PingResultsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<PingResults>();
	int IDX_CDMS_DB_VERSION = DB.GetReaderOrdinal(rdr, "CDMS_DB_VERSION");
	int IDX_CI_BUILD_END = DB.GetReaderOrdinal(rdr, "CI_BUILD_END");
	int IDX_DB_RESTORE_FROM_PROD_DATE = DB.GetReaderOrdinal(rdr, "DB_RESTORE_FROM_PROD_DATE");
	int IDX_DbEnv = DB.GetReaderOrdinal(rdr, "DbEnv");
	int IDX_DbServer = DB.GetReaderOrdinal(rdr, "DbServer");
	int IDX_Source = DB.GetReaderOrdinal(rdr, "Source");
	int IDX_TimeStamp = DB.GetReaderOrdinal(rdr, "TimeStamp");
	
	while (rdr.Read()){
	ret.Add(new PingResults {
	CDMS_DB_VERSION = (IDX_CDMS_DB_VERSION < 0 || rdr.IsDBNull(IDX_CDMS_DB_VERSION)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CDMS_DB_VERSION),
	CI_BUILD_END = (IDX_CI_BUILD_END < 0 || rdr.IsDBNull(IDX_CI_BUILD_END)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CI_BUILD_END),
	DB_RESTORE_FROM_PROD_DATE = (IDX_DB_RESTORE_FROM_PROD_DATE < 0 || rdr.IsDBNull(IDX_DB_RESTORE_FROM_PROD_DATE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DB_RESTORE_FROM_PROD_DATE),
	DbEnv = (IDX_DbEnv < 0 || rdr.IsDBNull(IDX_DbEnv)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DbEnv),
	DbServer = (IDX_DbServer < 0 || rdr.IsDBNull(IDX_DbServer)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DbServer),
	Source = (IDX_Source < 0 || rdr.IsDBNull(IDX_Source)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_Source),
	TimeStamp = (IDX_TimeStamp < 0 || rdr.IsDBNull(IDX_TimeStamp)) ? default(Nullable<System.DateTime>) : rdr.GetFieldValue<Nullable<System.DateTime>>(IDX_TimeStamp)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class PingResults

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class PocEmp {
	
	[DataMember]
	public Nullable<System.Int32> emp_sid {set;get;}
	
	
	[DataMember]
	public System.String first_nm {set;get;}
	
	
	[DataMember]
	public System.String last_nm {set;get;}
	
	
	/*
	private static List<PocEmp> PocEmpFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<PocEmp>();
	int IDX_emp_sid = DB.GetReaderOrdinal(rdr, "emp_sid");
	int IDX_first_nm = DB.GetReaderOrdinal(rdr, "first_nm");
	int IDX_last_nm = DB.GetReaderOrdinal(rdr, "last_nm");
	
	while (rdr.Read()){
	ret.Add(new PocEmp {
	emp_sid = (IDX_emp_sid < 0 || rdr.IsDBNull(IDX_emp_sid)) ? default(Nullable<System.Int32>) : rdr.GetFieldValue<Nullable<System.Int32>>(IDX_emp_sid),
	first_nm = (IDX_first_nm < 0 || rdr.IsDBNull(IDX_first_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_first_nm),
	last_nm = (IDX_last_nm < 0 || rdr.IsDBNull(IDX_last_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_last_nm)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class PocEmp

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class ToolConstants {
	
	[DataMember]
	public System.String CNST_DESC {set;get;}
	
	
	[DataMember]
	public System.String CNST_NM {set;get;}
	
	
	[DataMember]
	public System.String CNST_VAL_TXT {set;get;}
	
	
	/*
	private static List<ToolConstants> ToolConstantsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<ToolConstants>();
	int IDX_CNST_DESC = DB.GetReaderOrdinal(rdr, "CNST_DESC");
	int IDX_CNST_NM = DB.GetReaderOrdinal(rdr, "CNST_NM");
	int IDX_CNST_VAL_TXT = DB.GetReaderOrdinal(rdr, "CNST_VAL_TXT");
	
	while (rdr.Read()){
	ret.Add(new ToolConstants {
	CNST_DESC = (IDX_CNST_DESC < 0 || rdr.IsDBNull(IDX_CNST_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_DESC),
	CNST_NM = (IDX_CNST_NM < 0 || rdr.IsDBNull(IDX_CNST_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_NM),
	CNST_VAL_TXT = (IDX_CNST_VAL_TXT < 0 || rdr.IsDBNull(IDX_CNST_VAL_TXT)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_VAL_TXT)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class ToolConstants

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class AdminConstant {
	
	[DataMember]
	public System.String CNST_DESC {set;get;}
	
	
	[DataMember]
	public System.String CNST_NM {set;get;}
	
	
	[DataMember]
	public System.Int32 CNST_SID {set;get;}
	
	
	[DataMember]
	public System.String CNST_VAL_TXT {set;get;}
	
	
	[DataMember]
	public System.Boolean UI_UPD_FLG {set;get;}
	
	
	/*
	private static List<AdminConstant> AdminConstantFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminConstant>();
	int IDX_CNST_DESC = DB.GetReaderOrdinal(rdr, "CNST_DESC");
	int IDX_CNST_NM = DB.GetReaderOrdinal(rdr, "CNST_NM");
	int IDX_CNST_SID = DB.GetReaderOrdinal(rdr, "CNST_SID");
	int IDX_CNST_VAL_TXT = DB.GetReaderOrdinal(rdr, "CNST_VAL_TXT");
	int IDX_UI_UPD_FLG = DB.GetReaderOrdinal(rdr, "UI_UPD_FLG");
	
	while (rdr.Read()){
	ret.Add(new AdminConstant {
	CNST_DESC = (IDX_CNST_DESC < 0 || rdr.IsDBNull(IDX_CNST_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_DESC),
	CNST_NM = (IDX_CNST_NM < 0 || rdr.IsDBNull(IDX_CNST_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_NM),
	CNST_SID = (IDX_CNST_SID < 0 || rdr.IsDBNull(IDX_CNST_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CNST_SID),
	CNST_VAL_TXT = (IDX_CNST_VAL_TXT < 0 || rdr.IsDBNull(IDX_CNST_VAL_TXT)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CNST_VAL_TXT),
	UI_UPD_FLG = (IDX_UI_UPD_FLG < 0 || rdr.IsDBNull(IDX_UI_UPD_FLG)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_UI_UPD_FLG)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminConstant

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class AdminApplications {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.String APP_CD {set;get;}
	
	
	[DataMember]
	public System.String APP_DESC {set;get;}
	
	
	[DataMember]
	public System.Int32 APP_SID {set;get;}
	
	
	[DataMember]
	public System.String APP_SUITE {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	/*
	private static List<AdminApplications> AdminApplicationsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminApplications>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_APP_CD = DB.GetReaderOrdinal(rdr, "APP_CD");
	int IDX_APP_DESC = DB.GetReaderOrdinal(rdr, "APP_DESC");
	int IDX_APP_SID = DB.GetReaderOrdinal(rdr, "APP_SID");
	int IDX_APP_SUITE = DB.GetReaderOrdinal(rdr, "APP_SUITE");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	
	while (rdr.Read()){
	ret.Add(new AdminApplications {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_ACTV_IND),
	APP_CD = (IDX_APP_CD < 0 || rdr.IsDBNull(IDX_APP_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APP_CD),
	APP_DESC = (IDX_APP_DESC < 0 || rdr.IsDBNull(IDX_APP_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APP_DESC),
	APP_SID = (IDX_APP_SID < 0 || rdr.IsDBNull(IDX_APP_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_APP_SID),
	APP_SUITE = (IDX_APP_SUITE < 0 || rdr.IsDBNull(IDX_APP_SUITE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_APP_SUITE),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminApplications

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:51 PM
	///</summary>
	
	[DataContract]
	public partial class AdminDealType {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Int32 DEAL_ATRB_SID {set;get;}
	
	
	[DataMember]
	public System.String DEAL_TYPE_CD {set;get;}
	
	
	[DataMember]
	public System.String DEAL_TYPE_DESC {set;get;}
	
	
	[DataMember]
	public System.Int32 DEAL_TYPE_SID {set;get;}
	
	
	[DataMember]
	public System.Boolean PERFORM_CTST {set;get;}
	
	
	[DataMember]
	public System.Int32 TEMPLT_DEAL_NBR {set;get;}
	
	
	[DataMember]
	public System.Int32 TEMPLT_DEAL_SID {set;get;}
	
	
	[DataMember]
	public System.String TRKR_NBR_DT_LTR {set;get;}
	
	
	/*
	private static List<AdminDealType> AdminDealTypeFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminDealType>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_DEAL_ATRB_SID = DB.GetReaderOrdinal(rdr, "DEAL_ATRB_SID");
	int IDX_DEAL_TYPE_CD = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_CD");
	int IDX_DEAL_TYPE_DESC = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_DESC");
	int IDX_DEAL_TYPE_SID = DB.GetReaderOrdinal(rdr, "DEAL_TYPE_SID");
	int IDX_PERFORM_CTST = DB.GetReaderOrdinal(rdr, "PERFORM_CTST");
	int IDX_TEMPLT_DEAL_NBR = DB.GetReaderOrdinal(rdr, "TEMPLT_DEAL_NBR");
	int IDX_TEMPLT_DEAL_SID = DB.GetReaderOrdinal(rdr, "TEMPLT_DEAL_SID");
	int IDX_TRKR_NBR_DT_LTR = DB.GetReaderOrdinal(rdr, "TRKR_NBR_DT_LTR");
	
	while (rdr.Read()){
	ret.Add(new AdminDealType {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_ACTV_IND),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	DEAL_ATRB_SID = (IDX_DEAL_ATRB_SID < 0 || rdr.IsDBNull(IDX_DEAL_ATRB_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_DEAL_ATRB_SID),
	DEAL_TYPE_CD = (IDX_DEAL_TYPE_CD < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DEAL_TYPE_CD),
	DEAL_TYPE_DESC = (IDX_DEAL_TYPE_DESC < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_DEAL_TYPE_DESC),
	DEAL_TYPE_SID = (IDX_DEAL_TYPE_SID < 0 || rdr.IsDBNull(IDX_DEAL_TYPE_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_DEAL_TYPE_SID),
	PERFORM_CTST = (IDX_PERFORM_CTST < 0 || rdr.IsDBNull(IDX_PERFORM_CTST)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_PERFORM_CTST),
	TEMPLT_DEAL_NBR = (IDX_TEMPLT_DEAL_NBR < 0 || rdr.IsDBNull(IDX_TEMPLT_DEAL_NBR)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_TEMPLT_DEAL_NBR),
	TEMPLT_DEAL_SID = (IDX_TEMPLT_DEAL_SID < 0 || rdr.IsDBNull(IDX_TEMPLT_DEAL_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_TEMPLT_DEAL_SID),
	TRKR_NBR_DT_LTR = (IDX_TRKR_NBR_DT_LTR < 0 || rdr.IsDBNull(IDX_TRKR_NBR_DT_LTR)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_TRKR_NBR_DT_LTR)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminDealType

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class AdminRoleType {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.Int32 APP_SID {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Boolean IS_SNGL_SLCT {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TIER_CD {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_CD {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_DESC {set;get;}
	
	
	[DataMember]
	public System.String ROLE_TYPE_DSPLY_CD {set;get;}
	
	
	[DataMember]
	public System.Int32 ROLE_TYPE_SID {set;get;}
	
	
	/*
	private static List<AdminRoleType> AdminRoleTypeFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<AdminRoleType>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_APP_SID = DB.GetReaderOrdinal(rdr, "APP_SID");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_IS_SNGL_SLCT = DB.GetReaderOrdinal(rdr, "IS_SNGL_SLCT");
	int IDX_ROLE_TIER_CD = DB.GetReaderOrdinal(rdr, "ROLE_TIER_CD");
	int IDX_ROLE_TYPE_CD = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_CD");
	int IDX_ROLE_TYPE_DESC = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_DESC");
	int IDX_ROLE_TYPE_DSPLY_CD = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_DSPLY_CD");
	int IDX_ROLE_TYPE_SID = DB.GetReaderOrdinal(rdr, "ROLE_TYPE_SID");
	
	while (rdr.Read()){
	ret.Add(new AdminRoleType {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_ACTV_IND),
	APP_SID = (IDX_APP_SID < 0 || rdr.IsDBNull(IDX_APP_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_APP_SID),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	IS_SNGL_SLCT = (IDX_IS_SNGL_SLCT < 0 || rdr.IsDBNull(IDX_IS_SNGL_SLCT)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_IS_SNGL_SLCT),
	ROLE_TIER_CD = (IDX_ROLE_TIER_CD < 0 || rdr.IsDBNull(IDX_ROLE_TIER_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TIER_CD),
	ROLE_TYPE_CD = (IDX_ROLE_TYPE_CD < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_CD),
	ROLE_TYPE_DESC = (IDX_ROLE_TYPE_DESC < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_DESC),
	ROLE_TYPE_DSPLY_CD = (IDX_ROLE_TYPE_DSPLY_CD < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_DSPLY_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ROLE_TYPE_DSPLY_CD),
	ROLE_TYPE_SID = (IDX_ROLE_TYPE_SID < 0 || rdr.IsDBNull(IDX_ROLE_TYPE_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ROLE_TYPE_SID)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class AdminRoleType

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class SecurityActions {
	
	[DataMember]
	public System.String ACTN_CAT_CD {set;get;}
	
	
	[DataMember]
	public System.String ACTN_CD {set;get;}
	
	
	[DataMember]
	public System.String ACTN_DESC {set;get;}
	
	
	[DataMember]
	public System.Int32 ACTN_SID {set;get;}
	
	
	[DataMember]
	public System.DateTime CHG_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CHG_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.DateTime CRE_DTM {set;get;}
	
	
	[DataMember]
	public System.Int32 CRE_EMP_WWID {set;get;}
	
	
	[DataMember]
	public System.Int32 SRT_ORD {set;get;}
	
	
	[DataMember]
	public System.String WFSTG_ACTN_CD {set;get;}
	
	
	/*
	private static List<SecurityActions> SecurityActionsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<SecurityActions>();
	int IDX_ACTN_CAT_CD = DB.GetReaderOrdinal(rdr, "ACTN_CAT_CD");
	int IDX_ACTN_CD = DB.GetReaderOrdinal(rdr, "ACTN_CD");
	int IDX_ACTN_DESC = DB.GetReaderOrdinal(rdr, "ACTN_DESC");
	int IDX_ACTN_SID = DB.GetReaderOrdinal(rdr, "ACTN_SID");
	int IDX_CHG_DTM = DB.GetReaderOrdinal(rdr, "CHG_DTM");
	int IDX_CHG_EMP_WWID = DB.GetReaderOrdinal(rdr, "CHG_EMP_WWID");
	int IDX_CRE_DTM = DB.GetReaderOrdinal(rdr, "CRE_DTM");
	int IDX_CRE_EMP_WWID = DB.GetReaderOrdinal(rdr, "CRE_EMP_WWID");
	int IDX_SRT_ORD = DB.GetReaderOrdinal(rdr, "SRT_ORD");
	int IDX_WFSTG_ACTN_CD = DB.GetReaderOrdinal(rdr, "WFSTG_ACTN_CD");
	
	while (rdr.Read()){
	ret.Add(new SecurityActions {
	ACTN_CAT_CD = (IDX_ACTN_CAT_CD < 0 || rdr.IsDBNull(IDX_ACTN_CAT_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_CAT_CD),
	ACTN_CD = (IDX_ACTN_CD < 0 || rdr.IsDBNull(IDX_ACTN_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_CD),
	ACTN_DESC = (IDX_ACTN_DESC < 0 || rdr.IsDBNull(IDX_ACTN_DESC)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_ACTN_DESC),
	ACTN_SID = (IDX_ACTN_SID < 0 || rdr.IsDBNull(IDX_ACTN_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ACTN_SID),
	CHG_DTM = (IDX_CHG_DTM < 0 || rdr.IsDBNull(IDX_CHG_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CHG_DTM),
	CHG_EMP_WWID = (IDX_CHG_EMP_WWID < 0 || rdr.IsDBNull(IDX_CHG_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CHG_EMP_WWID),
	CRE_DTM = (IDX_CRE_DTM < 0 || rdr.IsDBNull(IDX_CRE_DTM)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_CRE_DTM),
	CRE_EMP_WWID = (IDX_CRE_EMP_WWID < 0 || rdr.IsDBNull(IDX_CRE_EMP_WWID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CRE_EMP_WWID),
	SRT_ORD = (IDX_SRT_ORD < 0 || rdr.IsDBNull(IDX_SRT_ORD)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_SRT_ORD),
	WFSTG_ACTN_CD = (IDX_WFSTG_ACTN_CD < 0 || rdr.IsDBNull(IDX_WFSTG_ACTN_CD)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_WFSTG_ACTN_CD)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class SecurityActions

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class LogConfig {
	
	[DataMember]
	public System.Boolean IsActive {set;get;}
	
	
	[DataMember]
	public System.String MsgSrc {set;get;}
	
	
	/*
	private static List<LogConfig> LogConfigFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<LogConfig>();
	int IDX_IsActive = DB.GetReaderOrdinal(rdr, "IsActive");
	int IDX_MsgSrc = DB.GetReaderOrdinal(rdr, "MsgSrc");
	
	while (rdr.Read()){
	ret.Add(new LogConfig {
	IsActive = (IDX_IsActive < 0 || rdr.IsDBNull(IDX_IsActive)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_IsActive),
	MsgSrc = (IDX_MsgSrc < 0 || rdr.IsDBNull(IDX_MsgSrc)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_MsgSrc)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class LogConfig

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class CustomerDivision {
	
	[DataMember]
	public System.Boolean ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.String CUST_CAT {set;get;}
	
	
	[DataMember]
	public System.String CUST_DIV_NM {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_DIV_NM_SID {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_MBR_SID {set;get;}
	
	
	[DataMember]
	public System.String CUST_NM {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_NM_SID {set;get;}
	
	
	[DataMember]
	public System.String CUST_TYPE {set;get;}
	
	
	[DataMember]
	public System.String HOSTED_GEO {set;get;}
	
	
	/*
	private static List<CustomerDivision> CustomerDivisionFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<CustomerDivision>();
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_CUST_CAT = DB.GetReaderOrdinal(rdr, "CUST_CAT");
	int IDX_CUST_DIV_NM = DB.GetReaderOrdinal(rdr, "CUST_DIV_NM");
	int IDX_CUST_DIV_NM_SID = DB.GetReaderOrdinal(rdr, "CUST_DIV_NM_SID");
	int IDX_CUST_MBR_SID = DB.GetReaderOrdinal(rdr, "CUST_MBR_SID");
	int IDX_CUST_NM = DB.GetReaderOrdinal(rdr, "CUST_NM");
	int IDX_CUST_NM_SID = DB.GetReaderOrdinal(rdr, "CUST_NM_SID");
	int IDX_CUST_TYPE = DB.GetReaderOrdinal(rdr, "CUST_TYPE");
	int IDX_HOSTED_GEO = DB.GetReaderOrdinal(rdr, "HOSTED_GEO");
	
	while (rdr.Read()){
	ret.Add(new CustomerDivision {
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Boolean) : rdr.GetFieldValue<System.Boolean>(IDX_ACTV_IND),
	CUST_CAT = (IDX_CUST_CAT < 0 || rdr.IsDBNull(IDX_CUST_CAT)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_CAT),
	CUST_DIV_NM = (IDX_CUST_DIV_NM < 0 || rdr.IsDBNull(IDX_CUST_DIV_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_DIV_NM),
	CUST_DIV_NM_SID = (IDX_CUST_DIV_NM_SID < 0 || rdr.IsDBNull(IDX_CUST_DIV_NM_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_DIV_NM_SID),
	CUST_MBR_SID = (IDX_CUST_MBR_SID < 0 || rdr.IsDBNull(IDX_CUST_MBR_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_MBR_SID),
	CUST_NM = (IDX_CUST_NM < 0 || rdr.IsDBNull(IDX_CUST_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_NM),
	CUST_NM_SID = (IDX_CUST_NM_SID < 0 || rdr.IsDBNull(IDX_CUST_NM_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_NM_SID),
	CUST_TYPE = (IDX_CUST_TYPE < 0 || rdr.IsDBNull(IDX_CUST_TYPE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_TYPE),
	HOSTED_GEO = (IDX_HOSTED_GEO < 0 || rdr.IsDBNull(IDX_HOSTED_GEO)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_HOSTED_GEO)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class CustomerDivision

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class MyCustomersInformation {
	
	[DataMember]
	public System.Int32 ACCS_TYPE {set;get;}
	
	
	[DataMember]
	public System.Int32 ACTV_IND {set;get;}
	
	
	[DataMember]
	public System.String CUST_CAT {set;get;}
	
	
	[DataMember]
	public System.String CUST_CHNL {set;get;}
	
	
	[DataMember]
	public System.String CUST_DISP_NM {set;get;}
	
	
	[DataMember]
	public System.String CUST_DIV_NM {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_DIV_NM_SID {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_LVL_SID {set;get;}
	
	
	[DataMember]
	public System.String CUST_NM {set;get;}
	
	
	[DataMember]
	public System.Int32 CUST_NM_SID {set;get;}
	
	
	[DataMember]
	public System.String CUST_TYPE {set;get;}
	
	
	[DataMember]
	public System.Int32 DEAL_FLG {set;get;}
	
	
	[DataMember]
	public System.String HOSTED_GEO {set;get;}
	
	
	[DataMember]
	public System.Int32 MAIL_NOTIF_FLG {set;get;}
	
	
	/*
	private static List<MyCustomersInformation> MyCustomersInformationFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<MyCustomersInformation>();
	int IDX_ACCS_TYPE = DB.GetReaderOrdinal(rdr, "ACCS_TYPE");
	int IDX_ACTV_IND = DB.GetReaderOrdinal(rdr, "ACTV_IND");
	int IDX_CUST_CAT = DB.GetReaderOrdinal(rdr, "CUST_CAT");
	int IDX_CUST_CHNL = DB.GetReaderOrdinal(rdr, "CUST_CHNL");
	int IDX_CUST_DISP_NM = DB.GetReaderOrdinal(rdr, "CUST_DISP_NM");
	int IDX_CUST_DIV_NM = DB.GetReaderOrdinal(rdr, "CUST_DIV_NM");
	int IDX_CUST_DIV_NM_SID = DB.GetReaderOrdinal(rdr, "CUST_DIV_NM_SID");
	int IDX_CUST_LVL_SID = DB.GetReaderOrdinal(rdr, "CUST_LVL_SID");
	int IDX_CUST_NM = DB.GetReaderOrdinal(rdr, "CUST_NM");
	int IDX_CUST_NM_SID = DB.GetReaderOrdinal(rdr, "CUST_NM_SID");
	int IDX_CUST_TYPE = DB.GetReaderOrdinal(rdr, "CUST_TYPE");
	int IDX_DEAL_FLG = DB.GetReaderOrdinal(rdr, "DEAL_FLG");
	int IDX_HOSTED_GEO = DB.GetReaderOrdinal(rdr, "HOSTED_GEO");
	int IDX_MAIL_NOTIF_FLG = DB.GetReaderOrdinal(rdr, "MAIL_NOTIF_FLG");
	
	while (rdr.Read()){
	ret.Add(new MyCustomersInformation {
	ACCS_TYPE = (IDX_ACCS_TYPE < 0 || rdr.IsDBNull(IDX_ACCS_TYPE)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ACCS_TYPE),
	ACTV_IND = (IDX_ACTV_IND < 0 || rdr.IsDBNull(IDX_ACTV_IND)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_ACTV_IND),
	CUST_CAT = (IDX_CUST_CAT < 0 || rdr.IsDBNull(IDX_CUST_CAT)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_CAT),
	CUST_CHNL = (IDX_CUST_CHNL < 0 || rdr.IsDBNull(IDX_CUST_CHNL)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_CHNL),
	CUST_DISP_NM = (IDX_CUST_DISP_NM < 0 || rdr.IsDBNull(IDX_CUST_DISP_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_DISP_NM),
	CUST_DIV_NM = (IDX_CUST_DIV_NM < 0 || rdr.IsDBNull(IDX_CUST_DIV_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_DIV_NM),
	CUST_DIV_NM_SID = (IDX_CUST_DIV_NM_SID < 0 || rdr.IsDBNull(IDX_CUST_DIV_NM_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_DIV_NM_SID),
	CUST_LVL_SID = (IDX_CUST_LVL_SID < 0 || rdr.IsDBNull(IDX_CUST_LVL_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_LVL_SID),
	CUST_NM = (IDX_CUST_NM < 0 || rdr.IsDBNull(IDX_CUST_NM)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_NM),
	CUST_NM_SID = (IDX_CUST_NM_SID < 0 || rdr.IsDBNull(IDX_CUST_NM_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_NM_SID),
	CUST_TYPE = (IDX_CUST_TYPE < 0 || rdr.IsDBNull(IDX_CUST_TYPE)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_CUST_TYPE),
	DEAL_FLG = (IDX_DEAL_FLG < 0 || rdr.IsDBNull(IDX_DEAL_FLG)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_DEAL_FLG),
	HOSTED_GEO = (IDX_HOSTED_GEO < 0 || rdr.IsDBNull(IDX_HOSTED_GEO)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_HOSTED_GEO),
	MAIL_NOTIF_FLG = (IDX_MAIL_NOTIF_FLG < 0 || rdr.IsDBNull(IDX_MAIL_NOTIF_FLG)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_MAIL_NOTIF_FLG)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class MyCustomersInformation

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class MyCustomersSoldTo {
	
	[DataMember]
	public System.String cust_disp_nm {set;get;}
	
	
	[DataMember]
	public System.Int32 cust_div_nm_sid {set;get;}
	
	
	[DataMember]
	public System.String cust_nm {set;get;}
	
	
	[DataMember]
	public System.String geo_nm {set;get;}
	
	
	[DataMember]
	public System.String sold_to_id {set;get;}
	
	
	/*
	private static List<MyCustomersSoldTo> MyCustomersSoldToFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<MyCustomersSoldTo>();
	int IDX_cust_disp_nm = DB.GetReaderOrdinal(rdr, "cust_disp_nm");
	int IDX_cust_div_nm_sid = DB.GetReaderOrdinal(rdr, "cust_div_nm_sid");
	int IDX_cust_nm = DB.GetReaderOrdinal(rdr, "cust_nm");
	int IDX_geo_nm = DB.GetReaderOrdinal(rdr, "geo_nm");
	int IDX_sold_to_id = DB.GetReaderOrdinal(rdr, "sold_to_id");
	
	while (rdr.Read()){
	ret.Add(new MyCustomersSoldTo {
	cust_disp_nm = (IDX_cust_disp_nm < 0 || rdr.IsDBNull(IDX_cust_disp_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_cust_disp_nm),
	cust_div_nm_sid = (IDX_cust_div_nm_sid < 0 || rdr.IsDBNull(IDX_cust_div_nm_sid)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_cust_div_nm_sid),
	cust_nm = (IDX_cust_nm < 0 || rdr.IsDBNull(IDX_cust_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_cust_nm),
	geo_nm = (IDX_geo_nm < 0 || rdr.IsDBNull(IDX_geo_nm)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_geo_nm),
	sold_to_id = (IDX_sold_to_id < 0 || rdr.IsDBNull(IDX_sold_to_id)) ? String.Empty : rdr.GetFieldValue<System.String>(IDX_sold_to_id)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class MyCustomersSoldTo

	///<summary>
	/// Class created via template - Do Not Modify!
	/// To modify this code, re-execute the template, or extend as partial.
	/// on JJYEH-MOBL
	/// by jjyeh
	/// at 11/30/2016 2:09:52 PM
	///</summary>
	
	[DataContract]
	public partial class CustomerQuarterDetails {
	
	[DataMember]
	public System.Int32 CUST_MBR_SID {set;get;}
	
	
	[DataMember]
	public System.DateTime QTR_END {set;get;}
	
	
	[DataMember]
	public System.Int16 QTR_NBR {set;get;}
	
	
	[DataMember]
	public System.DateTime QTR_STRT {set;get;}
	
	
	[DataMember]
	public System.Int16 YR_NBR {set;get;}
	
	
	/*
	private static List<CustomerQuarterDetails> CustomerQuarterDetailsFromReader(SqlDataReader rdr){
	// This helper method is template generated.
	// Refer to that template for details to modify this code.
	
	var ret = new List<CustomerQuarterDetails>();
	int IDX_CUST_MBR_SID = DB.GetReaderOrdinal(rdr, "CUST_MBR_SID");
	int IDX_QTR_END = DB.GetReaderOrdinal(rdr, "QTR_END");
	int IDX_QTR_NBR = DB.GetReaderOrdinal(rdr, "QTR_NBR");
	int IDX_QTR_STRT = DB.GetReaderOrdinal(rdr, "QTR_STRT");
	int IDX_YR_NBR = DB.GetReaderOrdinal(rdr, "YR_NBR");
	
	while (rdr.Read()){
	ret.Add(new CustomerQuarterDetails {
	CUST_MBR_SID = (IDX_CUST_MBR_SID < 0 || rdr.IsDBNull(IDX_CUST_MBR_SID)) ? default(System.Int32) : rdr.GetFieldValue<System.Int32>(IDX_CUST_MBR_SID),
	QTR_END = (IDX_QTR_END < 0 || rdr.IsDBNull(IDX_QTR_END)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_QTR_END),
	QTR_NBR = (IDX_QTR_NBR < 0 || rdr.IsDBNull(IDX_QTR_NBR)) ? default(System.Int16) : rdr.GetFieldValue<System.Int16>(IDX_QTR_NBR),
	QTR_STRT = (IDX_QTR_STRT < 0 || rdr.IsDBNull(IDX_QTR_STRT)) ? default(System.DateTime) : rdr.GetFieldValue<System.DateTime>(IDX_QTR_STRT),
	YR_NBR = (IDX_YR_NBR < 0 || rdr.IsDBNull(IDX_YR_NBR)) ? default(System.Int16) : rdr.GetFieldValue<System.Int16>(IDX_YR_NBR)
	});
	} // while
	return ret;
	}
	*/
	
	} // End of class CustomerQuarterDetails

}
